### ISSUE TITLE
Comparison to other filter apps

### ISSUE THREAD

**Issue by kousu** [UNFmontreal/Dcm2Bids#101]
After thinking through #68, I've realized that dcm2bids is essentially a small filter with a custom query language. It's _a lot_ like `sed` or `awk`, except it operates over MRI images instead of streams of text. A "config" is better thought of as a small program -- the same way `sed` and `awk` take small programs to process their input. Indeed, [sidecar.py](https://github.com/UNFmontreal/Dcm2Bids/blob/14ff8b1443010ab88ca32645c38cdc71c42499db/dcm2bids/sidecar.py) is the core of an _interpreter_ for those programs, and many of the features @arnaudbore has on the horizon look like adding more primitives to that language, like `<=`, `switch-case` and `lower()`.

It would be worthwhile to step back and do some lit review of this field to see what works and what doesn't.

**Comment by kousu** [comment]
Personally, I don't really think json is a great format for expressing programs in. But given that the core of dcm2bids is about processing .json sidecar files, there is probably a lot to be learned from the [`jq`](https://stedolan.github.io/jq/) and [jsonpath](https://jsonpath.com/) languages. `jq` started as a query language for json but quickly grew lots of kinds of operators (and loops for some reason; I don't think we need loops); for example, it has a complete implementation of regexes (https://stedolan.github.io/jq/manual/#RegularexpressionsPCRE), and a nice syntax for working with them: https://jqplay.org/jq?q=match(%5B%22foo%22%2C%20%22ig%22%5D)&j=%22foo%20bar%20FOO%22. I also think thinking about SQL is useful, since sidecars are essentially tabular data (except for `ImageType` and `ImageOrientationPatientDICOM`) -- and actually [some SQLs](https://www.postgresql.org/docs/13/functions-json.html) do support nested JSON queries.

**Comment by kousu** [comment]
I actually wonder if we could use `jq` or `jsonpath` directly as the query language.

For an example of how they can be integrated, check out how k8s does it: https://kubernetes.io/docs/reference/kubectl/jsonpath/

```
kubectl get pods -o=jsonpath="{range .items[*]}{.metadata.name}{\"\t\"}{.status.startTime}{\"\n\"}{end}"
```

I also think `awk`'s syntax is enlightening. I was enlightened by this blog post: https://tomayko.com/blog/2011/awkward-ruby. In `awk`, the basic data structure is a "record" consisting of "fields", which is by default a "line" separated by "spaces" (but you can configure that). You write programs like

```
filter1 {
  actions
}
filter2 {
  actions
}
filter3 {
  actions
}
```

each record is run through each filter in turn, performing any actions attached if matched, in order. We could translate our [json format](https://github.com/UNFmontreal/Dcm2Bids/blob/14ff8b1443010ab88ca32645c38cdc71c42499db/tests/data/config_test.json#L1) into almost-awk by:

```
BEGIN {
  MATCH="fnmatch"
}

SeriesDescription ~ /locali*/ {
  datatype=modality="localizer"
  ProcedureStepDescription="Modified by dcm2bids"
}

SeriesDescription ~ /*bold/ && ImageType ~= ["ORIG?NAL", "PRIMARY", "M", "ND", "MOSAIC"] { # list comparisons aren't part of awk natively
  datatype="func"
  modality="bold"
  customLabel="task-rest"
}

SeriesDescription == "DTI_FA" && ImageType[-1] == ["DTI_FA", "M"] {
  dataType=modality="dwi"
  customLabel="desc-fa00"
}
```

We should do a similar exercise with `jq` and `jsonpath`.

**Comment by arnaudbore** [comment]
From my point of view, I don't think about re-writing the way dcm2bids works.
Remember we want to keep dcm2bids compact and easy to use and so far the config file has proven to be efficient. 
I'm surely not thinking about all the little corners of what the coming features will uncover but I will make sure dcm2bids stay compact even if it means to not be able to expand dcm2bids.

**Comment by kousu** [comment]
Have no fear, I'm not suggesting diving into a rewrite. I'm just suggesting a framework about how to think about what dcm2bids does. I propose that we stop calling config files config files and start calling them "sorting scripts", and that as features get added to them we think about them in that light. dcm2bids is a small programming language, and that's a useful insight to have about it. I do think there could come a point where it is less confusing to change the syntax to use a custom Domain Specific Language (https://en.wikipedia.org/wiki/Domain-specific_language) than to keep trying to fit things into JSON. I don't think it is at that point yet.

**Comment by bwagnerwork** [comment]
I'm for a bit more flexibility in the config files/sorting scripts, but only if it could be done with minimal additional imports of non-standard Python base libraries.  More of preference towards none. If a complete change to the querying method is done I would hope it leans towards a language that isn't esoteric or flavor or the month.  It should also be performant.  My config files generally have 40 to 60 items in them.  I don't know of it that normal or not.

**Comment by arnaudbore** [comment]
New features are helping dcm2bids to be more flexible.
