### ISSUE TITLE
searchMethod re - new considerations

### ISSUE THREAD

**Issue by arnaudbore** [UNFmontreal/Dcm2Bids#102]
The `re` case uses `re.search`, which is the same as `re.match(name, ".* + pattern + ".*")`, i.e. it's an `in` not an `==` kind of comparison by default; the `fnmatch` case is inconsistent because it's an `==` kind of case by default, and needs you to wrap crtieria like `"*criteria*"` to get the `in` behaviour.

I think the `==` behaviour is better, so I would change `re.search` to `re.match` and leave `fnmatch` how it is already, but you could also fix it by auto-wrapping the `fnmatch` patterns in "*".

_Originally posted by @kousu in https://github.com/UNFmontreal/Dcm2Bids/pull/68#discussion_r528976429_

**Comment by kousu** [comment]
(could you edit this to remove the "slightly off-topic" part from my original comment? that was just about it being off-topic within that PR)
