### ISSUE TITLE
filter on nifti attributes

### ISSUE THREAD

**Issue by bwagnerwork** [UNFmontreal/Dcm2Bids#104]
It would be helpful to be able to query against nifti attributes.  For example dimensions of the data volume which aren't usually attainable from typical sidecar.  I have a functioning version at https://github.com/bwagnerwork/Dcm2Bids/commit/67391c8153534c3fe8ca7624090507a3907418a0 which could be made into a pull request if there is an interest.

**Comment by arnaudbore** [comment]
Not something we want to push forward we want to keep it dcm tag based for now.
