### ISSUE TITLE
Add citation section

### ISSUE THREAD

**Issue by jcohenadad** [UNFmontreal/Dcm2Bids#105]
This software need a "citation" section so that people know how to cite it

**Comment by weberam2** [comment]
Bump
Yes this would be good

**Comment by jcohenadad** [comment]
For now, let's use this issue for documentation. Here's the Zenodo DOI: https://zenodo.org/record/6596007/export/hx#.Yqo88ezMK3U

In the future, we might want to update/curate this citation @arnaudbore  (eg: it says 'Nick' as one of the author)

**Comment by arnaudbore** [comment]
Thank you @jcohenadad it took us a while but finally we've got our CITATION section :tada: 
We will also add it in the documentation for next release.

**Comment by jcohenadad** [comment]
I suggest adding an explicit section, at the top of the landing page of the README and in the documentation. Many people are not familiar with (and hence won’t find) the CITATION file.

**Comment by arnaudbore** [comment]
You are right, don't know if you knew but putting the citation.cff creates a new onglet "cite this repository" on the right in github.

**Comment by jcohenadad** [comment]
> You are right, don't know if you knew but putting the citation.cff creates a new onglet "cite this repository" on the right in github.

yes I knew about this and used it in some other projects, but doing an informal survey, I realized that people did not notice it, hence my suggestion to put it upfront, eg:
- https://ivadomed.org/
- https://shimming-toolbox.org/en/latest/
- https://spinalcordtoolbox.com/user_section/citing_sct.html
- https://github.com/ivadomed/model_seg_sctumor-edema-cavity_t2-t1_unet3d-multichannel#citation

Or keeping CITATION, but explicitly cross-referencing it:
- https://github.com/ivadomed/model_seg_mouse-sc_wm-gm_t1#citation

**Comment by arnaudbore** [comment]
Thank you !!!!!
