### ISSUE TITLE
IntendedFor JSON field suffix always ".nii.gz"

### ISSUE THREAD

**Issue by Michael-Monaldi** [UNFmontreal/Dcm2Bids#106]
Great fix for "add session in the path if using session #52"

If specifying dcm2niixoptions in the CONFIG file "-z n",
output files are not gzipped and are just NIFTIs. 

However, the "IntendedFor" field still shows 
"ses-*/func/sub-*_ses-*_task-*_***.nii.gz"

where it should instead show
"ses-*/func/sub-*_ses-*_task-*_***.nii"

Hope I explained this well enough. Should be a quick fix with a conditional

**Comment by arnaudbore** [comment]
Dear @Michael-Monaldi,

Thank you for raising this issue. Actually I'm about to create a new PR that will fix a couple of issues regarding the intendedFor field.
I will link this issue to the new PR so you can follow up with this.

Arnaud

**Comment by Michael-Monaldi** [comment]
Thank you! Excited to test it out!

**Comment by arnaudbore** [comment]
@Michael-Monaldi if you want to give it a try and give me some updates if it fixes your issue.
There is still some work to do about the tests (they fail because of the way they were designed).

**Comment by Michael-Monaldi** [comment]
Will test this within the next few days
