### ISSUE TITLE
Cannot build singularity image based on current recipe

### ISSUE THREAD

**Issue by pn2200** [UNFmontreal/Dcm2Bids#115]
I am trying to build a singularity image based on the current recipe in the file `Singularity`. It fails when trying to install `bids-validator` with error:
```
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "bids-validator"
```
The entire log is attached, but I think the issue is simply that the recipe is trying to install the latest version of `bids-validator`, which it cannot do with the old versions of `node.js` and `npm` that are available for this image.

[singularity_build.log](https://github.com/UNFmontreal/Dcm2Bids/files/5961535/singularity_build.log)

**Comment by arnaudbore** [comment]
Latest version fix this issue
