### ISSUE TITLE
conda package

### ISSUE THREAD

**Issue by arnaudbore** [UNFmontreal/Dcm2Bids#119]
I think it would be a great thing to have dcm2bids available as a conda forge package.
I need some help on this @SamGuay  ?

**Comment by SamGuay** [comment]
Should I list someone else other than me as maintainer(s) for this conda recipe?

You can see the recipe [here](https://github.com/SamGuay/staged-recipes/blob/dcm2bids/recipes/dcm2bids/meta.yaml).

Edit: I submitted, but anyone who wants to _help_ is welcome, just ping me on this issue! :)

**Comment by SamGuay** [comment]
Everything seems to be working! Here are the main badges if needed. 

[![Anaconda-Server Badge](https://anaconda.org/conda-forge/dcm2bids/badges/version.svg)](https://anaconda.org/conda-forge/dcm2bids)
[![Anaconda-Server Badge](https://anaconda.org/conda-forge/dcm2bids/badges/latest_release_date.svg)](https://anaconda.org/conda-forge/dcm2bids)
[![Anaconda-Server Badge](https://anaconda.org/conda-forge/dcm2bids/badges/latest_release_relative_date.svg)](https://anaconda.org/conda-forge/dcm2bids)
[![Anaconda-Server Badge](https://anaconda.org/conda-forge/dcm2bids/badges/downloads.svg)](https://anaconda.org/conda-forge/dcm2bids)
[![Anaconda-Server Badge](https://anaconda.org/conda-forge/dcm2bids/badges/installer/conda.svg)](https://conda.anaconda.org/conda-forge)
