### ISSUE TITLE
Update Zenodo to match released code

### ISSUE THREAD

**Issue by SamGuay** [UNFmontreal/Dcm2Bids#121]
If we follow the DOI, we see that the latest version hasn't been archived on Zenodo. It's either because
1. It used to be done manually and hasn't been done lately OR
1. The [automated archiving process](https://guides.github.com/activities/citable-code/) doesn't work anymore... Which was properly broken by having moved the repo to @UNFmontreal/dcm2bids _recently_. 

In either case, I think it should be fixed. It may require input from @cbedetti since he was probably the one who put did it back then if I'm not mistaken.

**Comment by cbedetti** [comment]
It was indeed the change of repo.
I needed to turn a switch on and off on the zenodo account.
It should be automatic for the next releases.

**Comment by SamGuay** [comment]
Great, thanks! Will reopen this issue if it doesn't update when the next version is released.
