### ISSUE TITLE
none-string value for 'name' param in compare function throws error

### ISSUE THREAD

**Issue by 1-w** [UNFmontreal/Dcm2Bids#126]
using "searchMethod" :  "re"

E.g. "EchoTime": 0.00492 in sidecar leads to following error thrown in re.search 

... 
  File "xyz/Dcm2Bids/dcm2bids/sidecar.py", line 179, in compare
    return bool(re.search(pattern, name))
  File "xyz/lib/python3.8/re.py", line 199, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
...

**Comment by Lestropie** [comment]
Am encountering the same error, but for the field "`EchoNumber`", which we must parse for multi-echo GRE SWI and SE T2 sequence data. Eager to see the fix in #127 pushed out in a version update. :+1:
