### ISSUE TITLE
possible to label with files run-01 if only instance?

### ISSUE THREAD

**Issue by dpagliaccio** [UNFmontreal/Dcm2Bids#129]
Hello
Is it possible to have dcm2bids label files with run notation even if there is only one of that type. Particularly, this has been an issue if some participants' data have two task runs (auto labelled as run-01 and run-02) but only one task run is collected for another participant, we would like it to have the run-01 label for consistency.
Thanks!

**Comment by dlevitas** [comment]
Hi @dpagliaccio ,

Would something like this not work in the configuration file?
```
{
   "descriptions": [
      {
         "dataType": "func",
         "modalityLabel": "bold",
         "customLabels": "task-bart_run-01",
         "criteria": {
            "SidecarFilename": "002*"
         },
         "sidecarChanges": {
            "TaskName": "bart"
         }
      },
     ....
}
     
```

Where you can set the run identifier using the `customLabels` field.

I'll also point you to this [Neurostars thread](https://neurostars.org/t/fmriprep-dropping-0-in-run-number-v20-2-0-v20-1-0/18223/3), where you may want to consider not zero-padding your run numbers. This is particularly true if you plan on processing your data with fMRIPrep, where the output files don't zero-padded, and then you won't have consistency with your BIDS dataset and the fMRIPrep output.

**Comment by arnaudbore** [comment]
Thank you @dlevitas for your help on this one. Hope everything work as expected @dpagliaccio. I'm closing this issue.
