### ISSUE TITLE
Dcm2bids tutorial pages is "off"

### ISSUE THREAD

**Issue by munoztd0** [UNFmontreal/Dcm2Bids#130]
Hello,

I don't know if you noticed but your https://unfmontreal.github.io/Dcm2Bids/2-tutorial pages are messed up.

Best,

David

**Comment by SamGuay** [comment]
Hi @munoztd0,

Thanks for letting us know! Indeed, the link you shared is definitely not working! May I know where you got this link from so I can fix this? 

The page for the tutorial is https://unfmontreal.github.io/Dcm2Bids/docs/2-tutorial/ so I think we forgot the `docs` wherever you found the link. 

Thanks,

**Comment by munoztd0** [comment]
It comes from the readme file.

**Comment by SamGuay** [comment]
Oh wow, thanks for having caught this, it is not fixed!
