### ISSUE TITLE
FALSE run?

### ISSUE THREAD

**Issue by jewellewej** [UNFmontreal/Dcm2Bids#132]
After I execute `dcm2bids -d ./RAW_Data -p 01  -c ./BIDS_config.json -o ./test --forceDcm2niix --clobber` in the command line, the results of each modality (anat, func) including 2 runs, json doc showed two different acquisition times. However, when I perform this in a python script `os.system(' '.join(['dcm2bids', '-d', source_dir, '-p', subject, '-c', con_doc, '-o',output_dir, '--forceDcm2niix --clobber']))`, results of only one run were saved. Then I use `dcm2bids_helper` to check my input data, the results indicated that there is one run in each modality, the results are consistent with that of Python script. Why there are 2 runs when I perform `dcm2bids` in the command line (In theory, the results should be the same no matter they from the script or command line, and actually, only one run included in my data).

**Comment by arnaudbore** [comment]
Hi @jewellewej ,
Do you still have this issue ? I'm back to work on dcm2bids and will be happy to help if needed.
