### ISSUE TITLE
Additional options for "searchMethod"

### ISSUE THREAD

**Issue by AlexHTreacher** [UNFmontreal/Dcm2Bids#133]
Hi All,

I'm running Dcm2Bids for some large public databases. When running Dcm2Bids, I'm using the "re" searchMethod to maximize flexibility. However, I'm currently running into issues with overlapping series descriptions. A very simple example: 'T2*' vs 'T2' vs 'T2Star' vs 'T2PD' vs 'T2FLAIR' vs 'T2_FLAIR' etc....  
I don't pretend to be a regular expressions wizard, but I've ended up with crazy expressions like "(?<!PD[-_+])(?<!PD_\\+_)(?<!T1_REPEA)(?<!FLAIR[-_])(T2|DUAL_TSE|Double_TSE|t2)(?!.*FLAIR|.*Flair|.*STAR|.*PD|.*dark)" as a criteria in my json file.
Is there a better way of doing this, perhaps using a look up table, or using a user defined function to map a dicom folder name to a modality label?

I'm sure I'm not the only person who has ran into this issue!

Thanks,
Alex

**Comment by arnaudbore** [comment]
It's been a long time but I think with dcm2bids 3.0 coming out soon with its new features, what you are trying to do it is going to be easier.
