### ISSUE TITLE
Do you know why dcm2bids is not working on my computer?

### ISSUE THREAD

**Issue by Kang1448** [UNFmontreal/Dcm2Bids#135]
Please see the following:

MacdeMacBook-Pro:build mac$ dcm2bids -d $HOME/learning/sub-08 -p 01 -c $HOME/learning/config3.json -o $HOME/learning --forceDcm2niix
Traceback (most recent call last):
  File "/Users/mac/Library/Python/3.8/bin/dcm2bids", line 8, in <module>
    sys.exit(main())
  File "/Users/mac/Library/Python/3.8/lib/python/site-packages/dcm2bids/dcm2bids.py", line 290, in main
    app = Dcm2bids(**vars(args))
  File "/Users/mac/Library/Python/3.8/lib/python/site-packages/dcm2bids/dcm2bids.py", line 51, in __init__
    self.config = load_json(config)
  File "/Users/mac/Library/Python/3.8/lib/python/site-packages/dcm2bids/utils.py", line 55, in load_json
    data = json.load(f, object_pairs_hook=OrderedDict)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 83 column 7 (char 1873)

**Comment by SamGuay** [comment]
Hi @Kang1448 ! 

I suspect it is related to your config file (`config3.json`), is it available on Github or can you attach it here?

In the last line you pasted, we can see that there is something missing at line 83, column 7 since the error message is telling you that it is expecting a value, but there is probably none or a character which makes dcm2bids think there should be a value right after it. Most of the time when dealing with JSON files, we forget or are missing commas here and there and this error happens.

You can also validate your config file with a JSON validator such as http://json-validator.com/.

Let me know how your debugging is going :)

**Comment by Kang1448** [comment]
INFO:dcm2bids.sidecar:No Pairing  <-  010_sub-08_IBL_fMRI_MB8_20210602121510
INFO:dcm2bids.sidecar:No Pairing  <-  011_sub-08_IBL_fMRI_MB8_20210602121510
INFO:dcm2bids.sidecar:No Pairing  <-  100_sub-08_MPRAGE_ADNI_P2_20210602121510
INFO:dcm2bids.sidecar:No Pairing  <-  100_sub-08_MPRAGE_ADNI_P2_20210602121510a
INFO:dcm2bids.sidecar:No Pairing  <-  101_sub-08_MPRAGE_ADNI_P2_20210602121510
INFO:dcm2bids.sidecar:No Pairing  <-  101_sub-08_MPRAGE_ADNI_P2_20210602121510a
INFO:dcm2bids.sidecar:sub-01/func/sub-01_task-IBL_run-01_sbref_0010 has 2 runs
INFO:dcm2bids.sidecar:Adding 'run' information to the acquisition
INFO:dcm2bids.dcm2bids:moving acquisitions into BIDS folder
Traceback (most recent call last):
  File "/Users/mac/Library/Python/3.8/bin/dcm2bids", line 8, in <module>
    sys.exit(main())
  File "/Users/mac/Library/Python/3.8/lib/python/site-packages/dcm2bids/dcm2bids.py", line 291, in main
    return app.run()
  File "/Users/mac/Library/Python/3.8/lib/python/site-packages/dcm2bids/dcm2bids.py", line 141, in run
    self.move(acq)
  File "/Users/mac/Library/Python/3.8/lib/python/site-packages/dcm2bids/dcm2bids.py", line 184, in move
    data = acquisition.dstSidecarData(self.config["descriptions"])
  File "/Users/mac/Library/Python/3.8/lib/python/site-packages/dcm2bids/structure.py", line 230, in dstSidecarData
    intendedDesc = descriptions[index]
IndexError: list index out of range

**Comment by Kang1448** [comment]
I am encountering a new problem. Here is the Json file I have: https://drive.google.com/file/d/1HIAJF-0a7rLGqgI4vOagiP-9N6ETYbQD/view?usp=sharing

**Comment by SamGuay** [comment]
Glad you caught the first error. 

The second error is hinted at again in the latest lines. In short, it complains regarding the 'IntendedFor' field in your config file. You have specified `2, 4, 8` but the number you put in this field should match the indexing in this particular config file. In case you didn't know, it starts from 0, so the first _item_ is the one you specified `"SidecarFilename": "002*"` (`T1w`), but it is position `0`, then the second item (`"SidecarFilename": "004*"` is `1`, etc. All of this to say that, based on your config file,  `8` doesn't exist.

Let me know if that helps,

Putting your (errored) config file in case it can help others in the future:

```json
{
   "descriptions": [
      {
         "dataType": "anat",
         "modalityLabel": "T1w",
         "criteria": {
            "SidecarFilename": "002*"
         }
      },
      {
         "dataType": "func",
         "modalityLabel": "sbref_0010",
         "customLabels": "task-SST_run-01",
         "criteria": {
            "SidecarFilename": "004*"
         },
         "sidecarChanges": {
            "TaskName": "SST"
         }
      },
      {
         "dataType": "func",
         "modalityLabel": "bold",
         "customLabels": "task-SST_run-01",
         "criteria": {
            "SidecarFilename": "005*"
         },
         "sidecarChanges": {
            "TaskName": "SST"
         }
      },
      {
         "dataType": "func",
         "modalityLabel": "sbref_0010",
         "customLabels": "task-IBL_run-01",
         "criteria": {
            "SidecarFilename": "006*"
         },
         "sidecarChanges": {
            "TaskName": "IBL"
         }
      },
      {
         "dataType": "func",
         "modalityLabel": "bold",
         "customLabels": "task-IBL_run-01",
         "criteria": {
            "SidecarFilename": "007*"
         },
         "sidecarChanges": {
            "TaskName": "IBL"
         }
      },
      {
         "dataType": "fmap",
         "modalityLabel": "magnitude1",
         "IntendedFor": [
            2,
            4,
	    8
         ],
         "criteria": {
            "SidecarFilename": "008*",
            "EchoTime": 0.00519
         }
      },
      {
         "dataType": "fmap",
         "modalityLabel": "phasediff",
         "IntendedFor": [
            2,
            4,
            8
         ],
         "criteria": {
            "SidecarFilename": "009*"
         },
         "sidecarChanges": {
            "EchoTime1": 0.00519,
            "EchoTime2": 0.00765
         }
      }
   ]
}
```

**Comment by Kang1448** [comment]
Hello, 
I modified the code but it still returns me the errors: 
{
   "descriptions": [
      {
         "dataType": "anat",
         "modalityLabel": "T1w",
         "criteria": {
            "SidecarFilename": "000*"
         }
      },
      {
         "dataType": "func",
         "modalityLabel": "sbref_0010",
         "customLabels": "task-SST_run-01",
         "criteria": {
            "SidecarFilename": "001*"
         },
         "sidecarChanges": {
            "TaskName": "SST"
         }
      },
      {
         "dataType": "func",
         "modalityLabel": "bold",
         "customLabels": "task-SST_run-01",
         "criteria": {
            "SidecarFilename": "002*"
         },
         "sidecarChanges": {
            "TaskName": "SST"
         }
      },
      {
         "dataType": "func",
         "modalityLabel": "sbref_0010",
         "customLabels": "task-IBL_run-01",
         "criteria": {
            "SidecarFilename": "003*"
         },
         "sidecarChanges": {
            "TaskName": "IBL"
         }
      },
      {
         "dataType": "func",
         "modalityLabel": "bold",
         "customLabels": "task-IBL_run-01",
         "criteria": {
            "SidecarFilename": "004*"
         },
         "sidecarChanges": {
            "TaskName": "IBL"
         }
      },
      {
         "dataType": "fmap",
         "modalityLabel": "magnitude1",
         "IntendedFor": [
            2,
            4,
	    8
         ],
         "criteria": {
            "SidecarFilename": "005*",
            "EchoTime": 0.00519
         }
      },
      {
         "dataType": "fmap",
         "modalityLabel": "phasediff",
         "IntendedFor": [
            2,
            4,
            8
         ],
         "criteria": {
            "SidecarFilename": "006*"
         },
         "sidecarChanges": {
            "EchoTime1": 0.00519,
            "EchoTime2": 0.00765
         }
      }
   ]
}

Here is the error: 
MacdeMacBook-Pro:build mac$ dcm2bids -d $HOME/learning/sub-08 -p 01 -c $HOME/learning/config3.json -o $HOME/learning --forceDcm2niix
INFO:dcm2bids.dcm2bids:--- dcm2bids start ---
INFO:dcm2bids.dcm2bids:OS:version: macOS-11.3.1-x86_64-i386-64bit
INFO:dcm2bids.dcm2bids:python:version: 3.8.2 (default, Jun  8 2021, 11:59:35) [Clang 12.0.5 (clang-1205.0.22.11)]
INFO:dcm2bids.dcm2bids:dcm2bids:version: 2.1.6
INFO:dcm2bids.dcm2bids:dcm2niix:version: v1.0.20210317
INFO:dcm2bids.dcm2bids:participant: sub-01
INFO:dcm2bids.dcm2bids:session: 
INFO:dcm2bids.dcm2bids:config: /Users/mac/learning/config3.json
INFO:dcm2bids.dcm2bids:BIDS directory: /Users/mac/learning
WARNING:dcm2bids.dcm2niix:Previous dcm2niix directory output found:
WARNING:dcm2bids.dcm2niix:/Users/mac/learning/tmp_dcm2bids/sub-01
WARNING:dcm2bids.dcm2niix:'force' argument is set to True
WARNING:dcm2bids.dcm2niix:Cleaning the previous directory and running dcm2niix
INFO:dcm2bids.utils:Running dcm2niix -b y -ba y -z y -f '%3s_%f_%p_%t' -o /Users/mac/learning/tmp_dcm2bids/sub-01 /Users/mac/learning/sub-08
INFO:dcm2bids.dcm2niix:Check log file for dcm2niix output
INFO:dcm2bids.sidecar:Sidecars pairing:
INFO:dcm2bids.sidecar:_task-SST_run-01_sbref_0010  <-  001_sub-08_localizer_20210602121510_i00001
INFO:dcm2bids.sidecar:_task-SST_run-01_sbref_0010  <-  001_sub-08_localizer_20210602121510_i00003
INFO:dcm2bids.sidecar:_task-SST_run-01_sbref_0010  <-  001_sub-08_localizer_20210602121510_i00002
INFO:dcm2bids.sidecar:_task-SST_run-01_bold  <-  002_sub-08_MPRAGE_ADNI_P2_20210602121510
INFO:dcm2bids.sidecar:_task-IBL_run-01_sbref_0010  <-  003_sub-08_MPRAGE_ADNI_P2_20210602121510
INFO:dcm2bids.sidecar:_task-IBL_run-01_bold  <-  004_sub-08_SST1_fMRI_MB8_20210602121510
INFO:dcm2bids.sidecar:No Pairing  <-  005_sub-08_SST1_fMRI_MB8_20210602121510
INFO:dcm2bids.sidecar:_phasediff  <-  006_sub-08_gre_field_mapping_20210602121510_e1
INFO:dcm2bids.sidecar:_phasediff  <-  006_sub-08_gre_field_mapping_20210602121510_e2
INFO:dcm2bids.sidecar:No Pairing  <-  007_sub-08_gre_field_mapping_20210602121510_e2_ph
INFO:dcm2bids.sidecar:No Pairing  <-  008_sub-08_gre_field_mapping_FOV210_BaseResolution70_20210602121510_e1
INFO:dcm2bids.sidecar:No Pairing  <-  008_sub-08_gre_field_mapping_FOV210_BaseResolution70_20210602121510_e2
INFO:dcm2bids.sidecar:No Pairing  <-  009_sub-08_gre_field_mapping_FOV210_BaseResolution70_20210602121510_e2_ph
INFO:dcm2bids.sidecar:No Pairing  <-  010_sub-08_IBL_fMRI_MB8_20210602121510
INFO:dcm2bids.sidecar:No Pairing  <-  011_sub-08_IBL_fMRI_MB8_20210602121510
INFO:dcm2bids.sidecar:No Pairing  <-  100_sub-08_MPRAGE_ADNI_P2_20210602121510
INFO:dcm2bids.sidecar:No Pairing  <-  100_sub-08_MPRAGE_ADNI_P2_20210602121510a
INFO:dcm2bids.sidecar:No Pairing  <-  101_sub-08_MPRAGE_ADNI_P2_20210602121510
INFO:dcm2bids.sidecar:No Pairing  <-  101_sub-08_MPRAGE_ADNI_P2_20210602121510a
INFO:dcm2bids.sidecar:sub-01/func/sub-01_task-SST_run-01_sbref_0010 has 3 runs
INFO:dcm2bids.sidecar:Adding 'run' information to the acquisition
INFO:dcm2bids.sidecar:sub-01/fmap/sub-01_phasediff has 2 runs
INFO:dcm2bids.sidecar:Adding 'run' information to the acquisition
INFO:dcm2bids.dcm2bids:moving acquisitions into BIDS folder
INFO:dcm2bids.dcm2bids:'/Users/mac/learning/sub-01/func/sub-01_task-SST_run-01_bold.nii.gz' already exists
INFO:dcm2bids.dcm2bids:Use clobber option to overwrite
INFO:dcm2bids.dcm2bids:'/Users/mac/learning/sub-01/func/sub-01_task-SST_run-01_bold.json' already exists
INFO:dcm2bids.dcm2bids:Use clobber option to overwrite
INFO:dcm2bids.dcm2bids:'/Users/mac/learning/sub-01/func/sub-01_task-IBL_run-01_bold.nii.gz' already exists
INFO:dcm2bids.dcm2bids:Use clobber option to overwrite
INFO:dcm2bids.dcm2bids:'/Users/mac/learning/sub-01/func/sub-01_task-IBL_run-01_bold.json' already exists
INFO:dcm2bids.dcm2bids:Use clobber option to overwrite
Traceback (most recent call last):
  File "/Users/mac/Library/Python/3.8/bin/dcm2bids", line 8, in <module>
    sys.exit(main())
  File "/Users/mac/Library/Python/3.8/lib/python/site-packages/dcm2bids/dcm2bids.py", line 291, in main
    return app.run()
  File "/Users/mac/Library/Python/3.8/lib/python/site-packages/dcm2bids/dcm2bids.py", line 141, in run
    self.move(acq)
  File "/Users/mac/Library/Python/3.8/lib/python/site-packages/dcm2bids/dcm2bids.py", line 184, in move
    data = acquisition.dstSidecarData(self.config["descriptions"])
  File "/Users/mac/Library/Python/3.8/lib/python/site-packages/dcm2bids/structure.py", line 230, in dstSidecarData
    intendedDesc = descriptions[index]
IndexError: list index out of range
MacdeMacBook-Pro:build mac$

**Comment by Kang1448** [comment]
Hello, 
I modified the code but it still returns me the errors: 
{
   "descriptions": [
      {
         "dataType": "anat",
         "modalityLabel": "T1w",
         "criteria": {
            "SidecarFilename": "000*"
         }
      },
      {
         "dataType": "func",
         "modalityLabel": "sbref_0010",
         "customLabels": "task-SST_run-01",
         "criteria": {
            "SidecarFilename": "001*"
         },
         "sidecarChanges": {
            "TaskName": "SST"
         }
      },
      {
         "dataType": "func",
         "modalityLabel": "bold",
         "customLabels": "task-SST_run-01",
         "criteria": {
            "SidecarFilename": "002*"
         },
         "sidecarChanges": {
            "TaskName": "SST"
         }
      },
      {
         "dataType": "func",
         "modalityLabel": "sbref_0010",
         "customLabels": "task-IBL_run-01",
         "criteria": {
            "SidecarFilename": "003*"
         },
         "sidecarChanges": {
            "TaskName": "IBL"
         }
      },
      {
         "dataType": "func",
         "modalityLabel": "bold",
         "customLabels": "task-IBL_run-01",
         "criteria": {
            "SidecarFilename": "004*"
         },
         "sidecarChanges": {
            "TaskName": "IBL"
         }
      },
      {
         "dataType": "fmap",
         "modalityLabel": "magnitude1",
         "IntendedFor": [
            2,
            4,
	    8
         ],
         "criteria": {
            "SidecarFilename": "005*",
            "EchoTime": 0.00519
         }
      },
      {
         "dataType": "fmap",
         "modalityLabel": "phasediff",
         "IntendedFor": [
            2,
            4,
            8
         ],
         "criteria": {
            "SidecarFilename": "006*"
         },
         "sidecarChanges": {
            "EchoTime1": 0.00519,
            "EchoTime2": 0.00765
         }
      }
   ]
}

Here is the error: 
MacdeMacBook-Pro:build mac$ dcm2bids -d $HOME/learning/sub-08 -p 01 -c $HOME/learning/config3.json -o $HOME/learning --forceDcm2niix
INFO:dcm2bids.dcm2bids:--- dcm2bids start ---
INFO:dcm2bids.dcm2bids:OS:version: macOS-11.3.1-x86_64-i386-64bit
INFO:dcm2bids.dcm2bids:python:version: 3.8.2 (default, Jun  8 2021, 11:59:35) [Clang 12.0.5 (clang-1205.0.22.11)]
INFO:dcm2bids.dcm2bids:dcm2bids:version: 2.1.6
INFO:dcm2bids.dcm2bids:dcm2niix:version: v1.0.20210317
INFO:dcm2bids.dcm2bids:participant: sub-01
INFO:dcm2bids.dcm2bids:session: 
INFO:dcm2bids.dcm2bids:config: /Users/mac/learning/config3.json
INFO:dcm2bids.dcm2bids:BIDS directory: /Users/mac/learning
WARNING:dcm2bids.dcm2niix:Previous dcm2niix directory output found:
WARNING:dcm2bids.dcm2niix:/Users/mac/learning/tmp_dcm2bids/sub-01
WARNING:dcm2bids.dcm2niix:'force' argument is set to True
WARNING:dcm2bids.dcm2niix:Cleaning the previous directory and running dcm2niix
INFO:dcm2bids.utils:Running dcm2niix -b y -ba y -z y -f '%3s_%f_%p_%t' -o /Users/mac/learning/tmp_dcm2bids/sub-01 /Users/mac/learning/sub-08
INFO:dcm2bids.dcm2niix:Check log file for dcm2niix output
INFO:dcm2bids.sidecar:Sidecars pairing:
INFO:dcm2bids.sidecar:_task-SST_run-01_sbref_0010  <-  001_sub-08_localizer_20210602121510_i00001
INFO:dcm2bids.sidecar:_task-SST_run-01_sbref_0010  <-  001_sub-08_localizer_20210602121510_i00003
INFO:dcm2bids.sidecar:_task-SST_run-01_sbref_0010  <-  001_sub-08_localizer_20210602121510_i00002
INFO:dcm2bids.sidecar:_task-SST_run-01_bold  <-  002_sub-08_MPRAGE_ADNI_P2_20210602121510
INFO:dcm2bids.sidecar:_task-IBL_run-01_sbref_0010  <-  003_sub-08_MPRAGE_ADNI_P2_20210602121510
INFO:dcm2bids.sidecar:_task-IBL_run-01_bold  <-  004_sub-08_SST1_fMRI_MB8_20210602121510
INFO:dcm2bids.sidecar:No Pairing  <-  005_sub-08_SST1_fMRI_MB8_20210602121510
INFO:dcm2bids.sidecar:_phasediff  <-  006_sub-08_gre_field_mapping_20210602121510_e1
INFO:dcm2bids.sidecar:_phasediff  <-  006_sub-08_gre_field_mapping_20210602121510_e2
INFO:dcm2bids.sidecar:No Pairing  <-  007_sub-08_gre_field_mapping_20210602121510_e2_ph
INFO:dcm2bids.sidecar:No Pairing  <-  008_sub-08_gre_field_mapping_FOV210_BaseResolution70_20210602121510_e1
INFO:dcm2bids.sidecar:No Pairing  <-  008_sub-08_gre_field_mapping_FOV210_BaseResolution70_20210602121510_e2
INFO:dcm2bids.sidecar:No Pairing  <-  009_sub-08_gre_field_mapping_FOV210_BaseResolution70_20210602121510_e2_ph
INFO:dcm2bids.sidecar:No Pairing  <-  010_sub-08_IBL_fMRI_MB8_20210602121510
INFO:dcm2bids.sidecar:No Pairing  <-  011_sub-08_IBL_fMRI_MB8_20210602121510
INFO:dcm2bids.sidecar:No Pairing  <-  100_sub-08_MPRAGE_ADNI_P2_20210602121510
INFO:dcm2bids.sidecar:No Pairing  <-  100_sub-08_MPRAGE_ADNI_P2_20210602121510a
INFO:dcm2bids.sidecar:No Pairing  <-  101_sub-08_MPRAGE_ADNI_P2_20210602121510
INFO:dcm2bids.sidecar:No Pairing  <-  101_sub-08_MPRAGE_ADNI_P2_20210602121510a
INFO:dcm2bids.sidecar:sub-01/func/sub-01_task-SST_run-01_sbref_0010 has 3 runs
INFO:dcm2bids.sidecar:Adding 'run' information to the acquisition
INFO:dcm2bids.sidecar:sub-01/fmap/sub-01_phasediff has 2 runs
INFO:dcm2bids.sidecar:Adding 'run' information to the acquisition
INFO:dcm2bids.dcm2bids:moving acquisitions into BIDS folder
INFO:dcm2bids.dcm2bids:'/Users/mac/learning/sub-01/func/sub-01_task-SST_run-01_bold.nii.gz' already exists
INFO:dcm2bids.dcm2bids:Use clobber option to overwrite
INFO:dcm2bids.dcm2bids:'/Users/mac/learning/sub-01/func/sub-01_task-SST_run-01_bold.json' already exists
INFO:dcm2bids.dcm2bids:Use clobber option to overwrite
INFO:dcm2bids.dcm2bids:'/Users/mac/learning/sub-01/func/sub-01_task-IBL_run-01_bold.nii.gz' already exists
INFO:dcm2bids.dcm2bids:Use clobber option to overwrite
INFO:dcm2bids.dcm2bids:'/Users/mac/learning/sub-01/func/sub-01_task-IBL_run-01_bold.json' already exists
INFO:dcm2bids.dcm2bids:Use clobber option to overwrite
Traceback (most recent call last):
  File "/Users/mac/Library/Python/3.8/bin/dcm2bids", line 8, in <module>
    sys.exit(main())
  File "/Users/mac/Library/Python/3.8/lib/python/site-packages/dcm2bids/dcm2bids.py", line 291, in main
    return app.run()
  File "/Users/mac/Library/Python/3.8/lib/python/site-packages/dcm2bids/dcm2bids.py", line 141, in run
    self.move(acq)
  File "/Users/mac/Library/Python/3.8/lib/python/site-packages/dcm2bids/dcm2bids.py", line 184, in move
    data = acquisition.dstSidecarData(self.config["descriptions"])
  File "/Users/mac/Library/Python/3.8/lib/python/site-packages/dcm2bids/structure.py", line 230, in dstSidecarData
    intendedDesc = descriptions[index]
IndexError: list index out of range
MacdeMacBook-Pro:build mac$

**Comment by SamGuay** [comment]
In your config file, I see that you still have 2, 4, and 8, but 8 is nowhere to be found. Which files are you targeting with fmap?
```json
         "IntendedFor": [
            2,
            4,
            8
         ],
```

Thanks

**Comment by Kang1448** [comment]
Hmmm, I deleted "8", it worked but seems the output only contains fmap and functional, functional seems incorrect as it should output two files as there are two distinct tasks. 

![IMG_5587](https://user-images.githubusercontent.com/67905967/127406198-4122fade-12ca-461a-b66e-50625150e35d.JPG)
![IMG_5585](https://user-images.githubusercontent.com/67905967/127406494-991463da-0d06-48f2-aee2-64e0708578df.JPG)

**Comment by Kang1448** [comment]
Hi, 
I modified the code, but it says my list is out of range, can you perhaps help me check again? Thanks!

   "descriptions": [
      {
         "dataType": "anat",
         "modalityLabel": "T1w",
         "criteria": {
            "SidecarFilename": "002*"
         }
      },
      {
         "dataType": "func",
         "modalityLabel": "sbref_0010",
         "customLabels": "task-SST_run-01",
         "criteria": {
            "SidecarFilename": "004*"
         },
         "sidecarChanges": {
            "TaskName": "SST"
         }
      },
      {
         "dataType": "func",
         "modalityLabel": "bold",
         "customLabels": "task-SST_run-01",
         "criteria": {
            "SidecarFilename": "005*"
         },
         "sidecarChanges": {
            "TaskName": "SST"
         }
      },
      {
         "dataType": "func",
         "modalityLabel": "sbref_0010",
         "customLabels": "task-IBL_run-01",
         "criteria": {
            "SidecarFilename": "0010*"
         },
         "sidecarChanges": {
            "TaskName": "IBL"
         }
      },
      {
         "dataType": "func",
         "modalityLabel": "bold",
         "customLabels": "task-IBL_run-01",
         "criteria": {
            "SidecarFilename": "0011*"
         },
         "sidecarChanges": {
            "TaskName": "IBL"
         }
      },
      {
         "dataType": "fmap",
         "modalityLabel": "magnitude1",
         "IntendedFor": [
            5,
            11
         ],
         "criteria": {
            "SidecarFilename": "008*",
            "EchoTime": 0.00519
         }
      },
      {
         "dataType": "fmap",
         "modalityLabel": "phasediff",
         "IntendedFor": [
           5,
           11
         ],
         "criteria": {
            "SidecarFilename": "009*"
         },
         "sidecarChanges": {
            "EchoTime1": 0.00519,
            "EchoTime2": 0.00765
         }
      }
   ]
}

**Comment by Kang1448** [comment]
This is the newest code I have, it says list is out of range:
{
"descriptions": [
{
"dataType": "anat",
"modalityLabel": "T1w",
"criteria": {
"SidecarFilename": "002*"
}
},
{
"dataType": "func",
"modalityLabel": "sbref_0010",
"customLabels": "task-SST_run-01",
"criteria": {
"SidecarFilename": "004*"
},
"sidecarChanges": {
"TaskName": "SST"
}
},
{
"dataType": "func",
"modalityLabel": "bold",
"customLabels": "task-SST_run-01",
"criteria": {
"SidecarFilename": "005*"
},
"sidecarChanges": {
"TaskName": "SST"
}
},
{
"dataType": "func",
"modalityLabel": "sbref_0010",
"customLabels": "task-IBL_run-01",
"criteria": {
"SidecarFilename": "0010*"
},
"sidecarChanges": {
"TaskName": "IBL"
}
},
{
"dataType": "func",
"modalityLabel": "bold",
"customLabels": "task-IBL_run-01",
"criteria": {
"SidecarFilename": "0011*"
},
"sidecarChanges": {
"TaskName": "IBL"
}
},
{
"dataType": "fmap",
"modalityLabel": "magnitude1",
"IntendedFor": [
8,
5,
11
],
"criteria": {
"SidecarFilename": "008*",
"EchoTime": 0.00519
}
},
{
"dataType": "fmap",
"modalityLabel": "phasediff",
"IntendedFor": [
9,
5,
11
],
"criteria": {
"SidecarFilename": "009*"
},
"sidecarChanges": {
"EchoTime1": 0.00519,
"EchoTime2": 0.00765
}
}
]
}

**Comment by SamGuay** [comment]
Glad to see you're are making some progress! 

So here's a couple of questions and thoughts first:
1. Did you follow the [tutorial](https://unfmontreal.github.io/Dcm2Bids/docs/2-tutorial/)? You can do the steps with your own data to help construct your config file. 
2. Did you run `dcm2bids_helper -d $HOME/learning/sub-08` to produce a converted set of niftii files with their sidecars?
  * Doing so will enable you to look into the `nameofsequence.json` to select robust criteria for the selection. What I mean by that is by picking `"SidecarFilename": "009*"` as your criterion, it may work for this particular subject. However, these numbers can change (eg., `009`) from one patient to another. 
  * Instead, have a look in the `sidecar.json` for each file you want to include in your config file and look for the field `SeriesDescription:`
  Here's how you could do it for your T1 for example (I don't have access to one of your sidecars, but I guess it would look like this). You want to select the MPRAGE _without_ the ND:
 ```json
      {
      "dataType": "anat",
      "modalityLabel": "T1w",
      "criteria": {
        "SeriesDescription": "MPRAGE_ADNI_P2"
      }
    },
```
3. the `IntendedFor` field is not according to the `00#` you put in criterion, but the index inside the config file. So in the latest config file that you pasted here, your T1w = 0, your second sequence = 1, etc. Try to change the `5, 9, 11` according to this [indexing](https://unfmontreal.github.io/Dcm2Bids/docs/3-configuration/#intendedfor). 

I have to hit the road, but tell me if it is working. 

Thank you for you patience, I think you have highlighted some points that need to be better documented :)

**Comment by SamGuay** [comment]
how is it going so far @Kang1448 ?

In case it can help you, here's a working example of a real config file a collaborator of mine used in the past: 

```json
{
    "descriptions": [
        {
            "dataType": "anat",
            "modalityLabel": "T1w",
            "criteria": {
                "SidecarFilename": "*t1*",
                "SeriesDescription": "t1_mprage_sag_p2_iso_192"
            }
        },
        {
            "dataType": "func",
            "modalityLabel": "bold",
            "customLabels": "task-rest_run-01",
            "criteria": {
                "SidecarFilename": "*Resting1*",
                "SeriesDescription": "*ep2d_bold_iPAT2_64ch_Resting1"
            },
            "sidecarChanges": {
                "TaskName": "rest"
            }
        },
        {
            "dataType": "func",
            "modalityLabel": "bold",
            "customLabels": "task-learning_run-01",
            "criteria": {
                "SidecarFilename": "*Run1*",
                "SeriesDescription": "*ep2d_bold_iPAT2_64ch_Run1*"
            },
            "sidecarChanges": {
                "TaskName": "learning"
            }
        },
        {
            "dataType": "func",
            "modalityLabel": "bold",
            "customLabels": "task-learning_run-02",
            "criteria": {
                "SidecarFilename": "*Run2*",
                "SeriesDescription": "*ep2d_bold_iPAT2_64ch_Run2*"
            },
            "sidecarChanges": {
                "TaskName": "learning"
            }
        },
        {
            "dataType": "func",
            "modalityLabel": "bold",
            "customLabels": "task-learning_run-03",
            "criteria": {
                "SidecarFilename": "*Run3*",
                "SeriesDescription": "*ep2d_bold_iPAT2_64ch_Run3*"
            },
            "sidecarChanges": {
                "TaskName": "learning"
            }
        },
        {
            "dataType": "func",
            "modalityLabel": "bold",
            "customLabels": "task-rest_run-02",
            "criteria": {
                "SidecarFilename": "*Resting2*",
                "SeriesDescription": "*ep2d_bold_iPAT2_64ch_Resting2*"
            },
            "sidecarChanges": {
                "TaskName": "rest"
            }
        },
        {
            "dataType": "fmap",
            "modalityLabel": "magnitude1",
            "SeriesDescription": "*gre_field_mapping_*",
            "criteria": {
                "SidecarFilename": "*e1*",
                "EchoTime": 0.00519
            },
            "IntendedFor": [
                1,
                2,
                3,
                4,
                5
            ]
        },
        {
            "dataType": "fmap",
            "modalityLabel": "magnitude2",
            "SeriesDescription": "*gre_field_mapping_*",
            "criteria": {
                "SidecarFilename": "*e2.json",
                "EchoTime": 0.00765
            },
            "IntendedFor": [
                1,
                2,
                3,
                4,
                5
            ]
        },
        {
            "dataType": "fmap",
            "modalityLabel": "phasediff",
            "SeriesDescription": "*gre_field_mapping_*",
            "criteria": {
                "SidecarFilename": "*ph*"
            },
            "sidecarChanges": {
                "EchoTime1": 0.00519,
                "EchoTime2": 0.00765
            },
            "IntendedFor": [
                1,
                2,
                3,
                4,
                5
            ]
        }
    ]
}
```

**Comment by Kang1448** [comment]
Hello,
May I know what the source of my error is?
File Path: Quick validation failed - the general folder structure does not resemble a BIDS dataset. Have you chosen the right folder (with “sub-*/” subfolders)? Check for structural/naming issues and presence of at least one subject.

Type:		Error
File:		sub-01
Reason:		Quick validation failed - the general folder structure does not resemble a BIDS dataset. Have you chosen the right folder (with "sub-*/" subfolders)? Check for structural/naming issues and presence of at least one subject.


https://drive.google.com/file/d/1NlKL5Zx0QqXYn6e0T32xa_re_altM0wO/view?usp=sharing

**Comment by arnaudbore** [comment]
It's been a while.... @Kang1448 did you manage to make dcm2bids work as you expected ? 
dcm2bids does not "BIDS" validate the output. It's a tool to reach this goal but it also gives flexibility so the user can do whatever he wants.

**Comment by arnaudbore** [comment]
@Kang1448 I'm closing this issue since it was not a :bug: in the program. Feel free to post on [neurostars.org](https://neurostars.org/) with the tag dcm2bids if you need help in the future.
