### ISSUE TITLE
file name containing custom labels is not necessarily bids conform 

### ISSUE THREAD

**Issue by 1-w** [UNFmontreal/Dcm2Bids#136]
E.g. the returned filename sub-01_\<custom label>\_\<modality>.json/.nii.gz is not BIDS conform. 
It should produce sub-01\_**acq-**\<custom label>\_\<modality>.json/.nii.gz instead.

After looking at the customLabels examples I see the customLabels string needs to be BIDS conform already. Perhaps an enhancement would be to make customLabels an object with {<entity>: <label>} syntax for better usability.

**Comment by arnaudbore** [comment]
Since #157 we added a couple of warning for such cases. 
We still want to give people the flexibility needed to do what they want.
