### ISSUE TITLE
List is out of range, do you know why?

### ISSUE THREAD

**Issue by Kang1448** [UNFmontreal/Dcm2Bids#137]
{
   "descriptions": [
      {
         "dataType": "anat",
         "modalityLabel": "T1w",
         "criteria": {
            "SidecarFilename": "002*"
         }
      },
      {
         "dataType": "func",
         "modalityLabel": "sbref_0010",
         "customLabels": "task-SST_run-01",
         "criteria": {
            "SidecarFilename": "004*"
         },
         "sidecarChanges": {
            "TaskName": "SST"
         }
      },
      {
         "dataType": "func",
         "modalityLabel": "bold",
         "customLabels": "task-SST_run-01",
         "criteria": {
            "SidecarFilename": "005*"
         },
         "sidecarChanges": {
            "TaskName": "SST"
         }
      },
      {
         "dataType": "func",
         "modalityLabel": "sbref_0010",
         "customLabels": "task-IBL_run-01",
         "criteria": {
            "SidecarFilename": "0010*"
         },
         "sidecarChanges": {
            "TaskName": "IBL"
         }
      },
      {
         "dataType": "func",
         "modalityLabel": "bold",
         "customLabels": "task-IBL_run-01",
         "criteria": {
            "SidecarFilename": "0011*"
         },
         "sidecarChanges": {
            "TaskName": "IBL"
         }
      },
      {
         "dataType": "fmap",
         "modalityLabel": "magnitude1",
         "IntendedFor": [
            8,
            5,
            11
         ],
         "criteria": {
            "SidecarFilename": "008*",
            "EchoTime": 0.00519
         }
      },
      {
         "dataType": "fmap",
         "modalityLabel": "phasediff",
         "IntendedFor": [
           9,
           5,
           11
         ],
         "criteria": {
            "SidecarFilename": "009*"
         },
         "sidecarChanges": {
            "EchoTime1": 0.00519,
            "EchoTime2": 0.00765
         }
      }
   ]
}

**Comment by SamGuay** [comment]
Hi @Kang1448, I will close this issue and follow up with you on the other one you opened last week (#135).
