### ISSUE TITLE
IntendedFor references fields that do not exist on dataset with multiple runs

### ISSUE THREAD

**Issue by aketchum15** [UNFmontreal/Dcm2Bids#138]
as mentioned in [this ](https://github.com/UNFmontreal/Dcm2Bids/issues/93#issue-745920495)issue using the intendedFor field does not result in references to real files in the final sidecars.
when running on a dataset with multiple runs the intendedfor parsing will result in list of file names that do not include any run tags. For example I have 2 different functional datatypes each with 2 runs. The expected intended for list would be something similar to:
`IntendedFor: ["func/sub-SUB_task-MID_run-01_bold.nii.gz",
"func/sub-SUB_task-MID_run-02_bold.nii.gz",
"func/sub-SUB_task-SSI_run-01_bold.nii.gz",
"func/sub-SUB_task-SSI_run-02_bold.nii.gz"
]`
but instead it results in:
`IntendedFor: ["func/sub-SUB_task-SSI_bold.nii.gz",
"func/sub-SUB_task-SSI_bold.nii.gz",
"func/sub-SUB_task-MID_bold.nii.gz",
"func/sub-SUB_task-MID_bold.nii.gz"
]`

**Comment by Lestropie** [comment]
Bumping as my lab has encountered the same issue in our data.

**Comment by walkerped** [comment]
I'm also having issues with this. dcm2bids automatically adds the run tag if it finds that there are two runs for the same subject-session-task, but only adds a single entry to the intendedFor field, with no run label.  Similarly, if a task is missing for a given subject-session dcm2bids is still adding an entry to the intendedFor field for the task to the fieldmap, resulting in the subject failing bids validator.

**Comment by arnaudbore** [comment]
@Lestropie , @walkerped  @aketchum15  
This has been fixed :tada: . Please check the master. A new release will come.

**Comment by bkossows** [comment]
hi @arnaudbore,
I think I've faced the same problem using the newest 3.1.1. My config file is as follows:
```bash
{
  "descriptions": [
    {
      "datatype": "anat",
      "suffix": "T1w",
      "criteria": {
        "SeriesDescription": "anat_t1w"
      }
    },
    {
      "id": "fmri",
      "datatype": "func",
      "suffix": "bold",
      "criteria": {
        "SeriesDescription": "task-fmri*"
      },
      "sidecar_changes": {
        "TaskName": "test"
      }
    },
    {
      "datatype": "fmap",
      "suffix": "epi",
      "criteria": {
        "SeriesDescription": "SpinEchoFieldMap*"
      },
      "sidecar_changes": {
        "intendedFor": ["fmri"]
      }
    }
  ]
}
```
I've got to runs of the same task:
```bash
sub-B352/
├── anat
│   ├── sub-B352_T1w.json
│   └── sub-B352_T1w.nii.gz
├── fmap
│   ├── sub-B352_dir-AP_epi.json
│   ├── sub-B352_dir-AP_epi.nii.gz
│   ├── sub-B352_dir-PA_epi.json
│   └── sub-B352_dir-PA_epi.nii.gz
└── func
    ├── sub-B352_task-fmri_run-01_bold.json
    ├── sub-B352_task-fmri_run-01_bold.nii.gz
    ├── sub-B352_task-fmri_run-02_bold.json
    └── sub-B352_task-fmri_run-02_bold.nii.gz
```
but my field map would not be applied to the 2nd session: `"intendedFor": "bids::sub-B352/func/sub-B352_task-fmri_run-01_bold.nii.gz"}`. I'd need to provide separate configs and ids for each run, then it works fine.

**Comment by arnaudbore** [comment]
@bkossows ,

I fixed this issue in the master but not released yet. 
Please give it a try :+1: 
I should release a new version by the end of the year or begining of the next one.
