### ISSUE TITLE
Tutorial nii.s being overwritten?

### ISSUE THREAD

**Issue by bgunasekera** [UNFmontreal/Dcm2Bids#141]
I have downloaded the sample data and I am following the tutorial 

https://unfmontreal.github.io/Dcm2Bids/docs/2-tutorial/
https://github.com/neurolabusc/dcm_qa_nih

Section 2: DICOM to NIfTI conversion gives this command: 
dcm2bids_helper -d sourcedata/dcm_qa_nih-master/In/
(Note, of course I removed the'-master' given that it's not in the sample data name)

This command will convert the DICOMs files to NIfTI files and save them inside tmp_dcm2bids/helper/ 
After running, it completes with the message
"Example in:
/home/k1754869/bids_tutorial/tmp_dcm2bids/helper" 

Inside that directory are only 16 files (see screenshot). Niis such as the Axial_EPI-FMRI* files are not there although their dicoms are indeed in sourcedata. I suspect the cause of this to be the that in sourcedata/dcm_qa_nih-master/In/ there are two directories named 20180918GE and 20180918Si. Within these, they have sub-directories named mr_0004 for example. As both directories contain names that overlap (as in the case of mr_0004) are files being overwritten? 

I have a second helper directory located in sourcedata
/sourcedata/dcm_qa_nih/tmp_dcm2bids/helper
However this is empty.

Apologies if this is an incredibly trivial question and I've missed something.

Best wishes,
Brandon 

![bids_error](https://user-images.githubusercontent.com/63005267/137478467-4dc6e392-75b7-4e74-b561-8916b2a5aeb3.jpg)

**Comment by SamGuay** [comment]
Hi @bgunasekera! 
Sorry for the delay :sweat_smile:. I hope you managed to find an answer to your question.

As mentioned in #142, what happened is the tutorial was last verified with a previous release of dcm2niix but a change in naming the files by dcm2niix was introduced in a newer release.

Once #162 is merged, the updated tutorial will work with the latest dcm2niix version!

Thank you for notifying us :)
