### ISSUE TITLE
Tutorials need update

### ISSUE THREAD

**Issue by Remi-Gau** [UNFmontreal/Dcm2Bids#142]
Trying to run the tutorial as is does not give the desired output.

https://unfmontreal.github.io/Dcm2Bids/docs/2-tutorial/#dicom-to-nifti-conversion

I do not get the following files mentioned in the tutorial:

-  004_In_Axial_EPI-FMRI_(Interleaved_I_to_S)_20180918114023.nii.gz
-  004_In_EPI_PE=PA_20180918121230.nii.gz
-  003_In_EPI_PE=AP_20180918121230.nii.gz

The `SeriesDescription` in the json files in helper do not correspond to what is in the tutorials: there are some extra underscores.

```bash
cat ../tmp_dcm2bids/helper/*.json | grep SeriesDes

        "SeriesDescription": "EPI PE=AP",
        "SeriesDescription": "Axial EPI-FMRI (Interleaved I to S)",
        "SeriesDescription": "EPI PE=PA",
        "SeriesDescription": "Axial EPI-FMRI (Sequential I to S)",
        "SeriesDescription": "EPI PE=RL",
        "SeriesDescription": "Axial EPI-FMRI (Interleaved S to I)",
        "SeriesDescription": "EPI PE=LR",
        "SeriesDescription": "Axial EPI-FMRI (Sequential S to I)",
```

Unless I am mistaken the desired `config.json` should look like this.

```json
{
    "descriptions": [
        {
            "dataType": "func",
            "modalityLabel": "bold",
            "customLabels": "task-rest",
            "criteria": {
                "SeriesDescription": "*Axial EPI-FMRI (Interleaved I to S)*"
            },
            "sidecarChanges": {
                "TaskName": "rest"
            }
        },
        {
            "dataType": "fmap",
            "modalityLabel": "epi",
            "customLabels": "dir-AP",
            "criteria": {
                "SeriesDescription": "*EPI PE=AP*"
            },
            "intendedFor": 0
        },
        {
            "dataType": "fmap",
            "modalityLabel": "epi",
            "customLabels": "dir-PA",
            "criteria": {
                "SeriesDescription": "*EPI PE=PA*"
            },
            "intendedFor": 0
        }
    ]
}

```

The code to reproduce is here: https://github.com/cpp-lln-lab/CPP_dicom2nii_BIDS/tree/master/demos/dicom2bids/code

**Comment by SamGuay** [comment]
Hi @Remi-Gau,

Thanks for the report, after investigation it appears dcm2niix has been behaving differently since the release of [v1.0.20210317](https://github.com/rordenlab/dcm2niix/releases/tag/v1.0.20210317) which is not the latest but the one before atm.

We'll make sure to update the tutorial accordingly.

**Comment by SamGuay** [comment]
Thanks for the heads up, the tutorial was updated in #162.
