### ISSUE TITLE
Query - matching based on series number rank

### ISSUE THREAD

**Issue by richardbeare** [UNFmontreal/Dcm2Bids#143]
Hi,
A question whether the following is possible. I have data which includes two functional tasks, and the parameters are identical apart from series number. I know I can match series number, but this is likely to be unreliable in the future, for example if one of the preceding scans is rerun. Is it possible to assign a different customLabel, for example, to the first match of a criteria and second match. One option I can imagine is disabling a criteria after it has been used, or including some kind of match rank criteria. 

Thanks

```
        {
            "dataType": "func",
            "modalityLabel": "bold",
            "customLabels": "task-enback1",
            "criteria": {
                "SeriesDescription": "func_task"
            }
        },
        {
            "dataType": "func",
            "modalityLabel": "bold",
            "customLabels": "task-enback2",
            "criteria": {
                "SeriesDescription": "func_task"
            }
        },
```

**Comment by arnaudbore** [comment]
Hi @richardbeare ,
I don't think dcm2bids will be able, even in the future, to do what you expect. 
I would encourage you to rename your acquisition at the console so you can have some key to grab in order to sort them easily.
