### ISSUE TITLE
Appending run entity violates ordering

### ISSUE THREAD

**Issue by Lestropie** [UNFmontreal/Dcm2Bids#144]
The [MRI entity table](https://bids-specification.readthedocs.io/en/latest/99-appendices/04-entity-table.html#magnetic-resonance-imaging) in the BIDS specification dictates the ordering of key-value pairs in BIDS-compliant file names. Of particular interest is the fact that `_run-#` appears before `_echo-#`.

Where there are multiple input series that match an entry in the config file, `dcm2bids` automatically appends the `_run-#` key-value to the end of the file name just prior to the suffix. However for multi-echo data, this violates the expected order of those entities (despite the fact that the BIDS validator is potentially not currently checking for such; bids-standard/bids-validator#1390), which in turn for me led to downstream processing issues (nipreps/fmriprep#2634).

**Comment by madisoth** [comment]
A fix for this would be much appreciated, but for now we've been able to work around the issue by making the `echo-` label part of `modalityLabel`, e.g. 

`"modalityLabel": "echo-1_bold"`, 

which will place the `echo-` field after the `run-` field.

**Comment by arnaudbore** [comment]
Should be fixed once #157 is merged.

**Comment by arnaudbore** [comment]
@madisoth @Lestropie if you want to give it a try. #157 has been merged. No release yet.
