### ISSUE TITLE
dcm2bids fail to convert field mapping file

### ISSUE THREAD

**Issue by YukunQu** [UNFmontreal/Dcm2Bids#147]
dcm2bids fail to convert field mapping file.
My field mapping file have e1,e2,e2_ph,. e2 and e2_ph only have different sidecar difference int his item —— ImageType;
e2 :"ImageType": ["ORIGINAL", "PRIMARY", "M", "ND"],
e2_ph ImageType": ["ORIGINAL", "PRIMARY", "P", "ND", "PHASE"],
but the dcm2bids can not recognize the sidecar difference between "ImageType".

It is very confuse me.

**Comment by YukunQu** [comment]
I think I figure out this problem.

**Comment by arnaudbore** [comment]
Hi @YukunQu ,
I know it's been a while but I want to know if you find out your issue.
Thank you in advance.

**Comment by YukunQu** [comment]
> 
@arnaudbore Oh, it's indeed been a while. If I remeber rightly, it is a logic mistake of mine. I add the " ["ORIGINAL", "PRIMARY", "P", "ND", "PHASE"]" to e2_ph's criteria aiming to distinguish e2 and e2_ph. But I didn't add the "["ORIGINAL", "PRIMARY", "M", "ND"]" to e2's criteria!!!.  I only add echo time. And the e2 and e2_ph both satisify the requirement.

I was naive enough to think that each file would only be rearrange and rename once. So the e2_ph been considered twice. 

This is my mistake. Sorry to bother you.

**Comment by arnaudbore** [comment]
Glad to see you fixed it. I'm going through all issues and PRs in order to fix most of the bugs, add most of the highly demanded features and release a new dcm2bids soon.
