### ISSUE TITLE
Automatic run number is not added to "IntendendFor" field in sidecar

### ISSUE THREAD

**Issue by awiehler** [UNFmontreal/Dcm2Bids#151]
Hi,
when there are multiple functional runs with the same task name, the run number is added automatically to the filename. This new filename including the run number is not copied to the "IndetendedFor" filed in the field map json. The fieldmap stays linked to the old filename without run number.

**Comment by arnaudbore** [comment]
It has been fixed in the master. A new release will come. Thank you
