### ISSUE TITLE
dcm2bids_scaffold needs a refresher

### ISSUE THREAD

**Issue by SamGuay** [UNFmontreal/Dcm2Bids#159]
While updating the tutorial, I noticed that the `dcm2bids_scaffold` function could get a little bit of love.  

- [ ] participants.tsv and participants.json should at least match.
- [ ] README could take some inspiration from the [BIDS Starter Kit's](https://github.com/bids-standard/bids-starter-kit/tree/main/templates).

In addition to these two updates, we could potentially add an optional flag for `rawdata/`, `phenotype/` directories, and probably others I'm forgetting atm.

**Comment by arnaudbore** [comment]
Done in #201
