### ISSUE TITLE
scaffold does not support over ride

### ISSUE THREAD

**Issue by GMerakis** [UNFmontreal/Dcm2Bids#170]
right now it's only callable from command line.
This does not play nicely with scaling and calling from scripts.

**Comment by NickGuAI** [comment]
I needed to run these conversions in large scale and in my scripts.
Found that directly changing source & call from code is easier than docker (where I need to spin up subproccess)

I created a fork to customize for my non-docker needs.
I see no need for it right now, but once done I'll write a doc for non-docker walk-through also
https://github.com/DasDominus/NonDocker_Dcm2Bids

**Comment by arnaudbore** [comment]
@DasDominus, I encourage you to submit a PR if you have ideas to improve dcm2bids. 
That will help the dcm2bids community.
