### ISSUE TITLE
'Dicom Images Not Found" Error

### ISSUE THREAD

**Issue by mmo8** [UNFmontreal/Dcm2Bids#174]
Hello,

I am attempting to run by dcm2bids_helper to create my config file, and I received the error that “Dicom images are not found”. I realized this error occurs because the dcm2bids helper by default only searches 5 paths/files deep within a subject ID. I believe there is a flag that can be used to change the depth so that dcm2bids helper can search deeper than 5 files, but I am unsure what the specific flag is to make this happen.

For reference, my dicom images are 6 files deep from my subject IDs. I’m currently running
"dcm2bids_helper -d /Users/Owner/Box "…etc to set the path to my subject IDs and their corresponding dicom images. When I moved one participant’s dicom images to make the path only 5 files deep, the dcm2bids_helper was successful. Any input on what can be done to change the search depth for dicom images to run the dcm2bids_helper would be great.

Thanks!

**Comment by arnaudbore** [comment]
Hey @mmo8 ,

Sorry it took me forever to respond. Did you figure out how to fix you issue? You should only need to change the dcm2niixOptions option in your config file.

See: https://unfmontreal.github.io/Dcm2Bids/docs/how-to/use-advanced-commands/#dcm2niixoptions
