### ISSUE TITLE
GE multi-echo fMRI data converted to run-01, run-02 instead of run-01_echo-01, run-01_echo-02, etc.

### ISSUE THREAD

**Issue by weberam2** [UNFmontreal/Dcm2Bids#175]
**Describe the bug**

I have acquired some multi-echo fMRI data on a 3T GE Discovery 750
When I go to convert this to nifit and bids, the echoes are interpreted as separate runs, instead of the same run with separate echoes

**To reproduce**

My BIDSconfig file is:

```
{
  "dcm2niixOptions": "-b y -ba y -z y -f '%3s_%f_%d_%r'",
  "descriptions": [
    {
      "dataType": "anat",
      "modalityLabel": "T1w",
      "criteria": {
        "SidecarFilename": "003*"
      }
    },
    {
      "dataType": "anat",
      "modalityLabel": "T2w",
      "criteria": {
        "SidecarFilename": "004*"
      }
    },
    {
      "dataType": "func",
      "modalityLabel": "bold",
      "customLabels": "dir-AP_task-rest",
      "criteria": {
        "SidecarFilename": "005*"
      },
      "TaskName": "rest"
    },
    {
      "dataType": "func",
      "modalityLabel": "bold",
      "customLabels": "dir-AP_task-rest",
      "criteria": {
        "SidecarFilename": "009*"
      },
      "TaskName": "rest"
    },
    {
      "dataType": "fmap",
      "modalityLabel": "epi",
      "customLabels": "dir-AP",
      "criteria": {
        "SidecarFilename": "100*"
      },
      "IntendedFor": [
        2,
        3
      ],
      "B0FieldIdentifier": "pepolar_fmap0"
    },
    {
      "dataType": "fmap",
      "modalityLabel": "epi",
      "customLabels": "dir-PA",
      "criteria": {
        "SidecarFilename": "008*"
      },
      "IntendedFor": [
        2,
        3
      ],
      "B0FieldIdentifier": "pepolar_fmap0"
    }
  ]
}
```

I then run

`dcm2bids` with the above config file and it seems dcm2niix thinks the echoes are separate runs...

**Expected behavior**

Instead of separate runs, I'd like it to be interpreted as one run, but separate echoes "run-01_echo-01" "run-01_echo-02" etc.

**Version**

Please report the complete version string:

Chris Rorden's dcm2niiX version v1.0.20211006 (JP2:OpenJPEG) (JP-LS:CharLS) GCC7.5.0 x86-64 (64-bit Linux) v1.0.20211006

Reorganising NIfTI files from dcm2niix into the Brain Imaging Data Structure
dcm2bids 2.1.6

**Comment by ColleenHughes** [comment]
Hi, not sure if you are still having this issue but the way to handle this is to create one entry in your BIDS_config.json for each echo. So customLabels: dir-AP_task-rest_echo-01 and then enter the EchoNumber: 1 in the criteria field so that each file is uniquely identified. In my experience, the first echo sometimes doesn't have the EchoNumber field in the json file but subsequent echoes do. You can add that field or use the EchoTime.

**Comment by weberam2** [comment]
Oh thanks! I'll try that :)
