### ISSUE TITLE
dots in nifti file names not correctly parsed

### ISSUE THREAD

**Issue by fedgiove** [UNFmontreal/Dcm2Bids#177]
Hello. It looks like that if a nifti has dots in filename the files moved to the "sub-" directory are not correctly renamed.

Eg, a file named abc.12345_67.nii.gz is renamed something like sub-01_ses_01_bold_ab.12345_67.nii.gz.  The "IntendedFor" in the associated fieldmap is correctly set to sub-01_ses_01_bold.nii.gz. This behaviour makes filename not bids compatible.

Dots in the filename are the result of %p switch in dcm2niix (whe have resolution in mm in the protocol names, eg 2.2 mm). There is an obvious workaround (don't use %p in dcm2niixOptions), nonetheless it would be nice to solve the issue.

**Comment by arnaudbore** [comment]
Can you provide some dicom so I can fix it ? 
@fedgiove ?
