### ISSUE TITLE
json files missing phase encoding direction, total readout time, slice timing, and echo spacing 

### ISSUE THREAD

**Issue by alexis-victoria** [UNFmontreal/Dcm2Bids#178]
Hello!

I am running dcm2bids with completely anonymized DICOMS that were obtained using a different scanner than I normally use, and the json files being output are missing the phase encoding direction. This differs from the json files that are output after I run dcm2bids with DICOMS obtained from the scanner I typically use. They have the phase encoding direction.

I compared the json files derived from the two scanners, and see that the Station Name, Procedure Step Description, and Protocol Name for each sequence are anonymized for the scanner I am having the issue with, and un-anonymized for the scanner I typically use.

Could this explain the issue I am having with the phase encoding directions not being present?

**Comment by arnaudbore** [comment]
Hi @alexis-victoria ,

Sorry for the long delay, you'll get more help (if still needed) if you were posting this issue on neurostars and add the tag dcm2niix since it's an issue with your dicoms and dcm2niix.

Best,
