### ISSUE TITLE
there is an attribute error in the underlying python package when running dcm2bids through singularity

### ISSUE THREAD

**Issue by seaguldee** [UNFmontreal/Dcm2Bids#179]
I've checked that I am running dcm2bids correctly through neurostars.org and seperatly with our IT department.  There appears to be an attribute error in the underlying python package?  Is this fixable?  I can't get it to run otherwise.  I am attaching the full output when our IT tried to run dcm2bids.  This seems like a strange issue as I've run dcm2bids previously but it's been a few months.  

Output when our IT folds tried to run dcm2bids....   

Thanks for providing the information. This is not quite what I expected, but I was able to run your container with some guessing. So, I did the following in a idev session under your account:

v320-001.ls6(933)$ ml tacc-singularity

v320-001.ls6(934)$ singularity exec /work/06953/jes6785/Containers/dcm2bids_latest.sif dcm2bids -d /scratch/06953/jes6785/NECTARY_DICOMS/ -o /scratch/06953/jes6785/Pre_Process_Test/sourcedata/ -c /scratch/06953/jes6785/NECTARY_DATA/code/config_2.json -p a017

ERROR: ld.so: object ‘/opt/apps/xalt/xalt/lib64/libxalt_init.so’ from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

INFO:dcm2bids.dcm2bids:— dcm2bids start —

INFO:dcm2bids.dcm2bids:OS:version: Linux-4.18.0-305.12.1.el8_4.x86_64-x86_64-with-glibc2.35

INFO:dcm2bids.dcm2bids:python:version: 3.10.4 (main, Apr 2 2022, 09:04:19) [GCC 11.2.0]

INFO:dcm2bids.dcm2bids:dcm2bids:version: 2.1.7

ERROR: ld.so: object ‘/opt/apps/xalt/xalt/lib64/libxalt_init.so’ from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

INFO:dcm2bids.dcm2bids:dcm2niix:version: v1.0.20201102

INFO:dcm2bids.dcm2bids:participant: sub-a017

INFO:dcm2bids.dcm2bids:session:

INFO:dcm2bids.dcm2bids:config: /scratch/06953/jes6785/NECTARY_DATA/code/config_2.json

INFO:dcm2bids.dcm2bids:BIDS directory: /scratch/06953/jes6785/Pre_Process_Test/sourcedata

Traceback (most recent call last):

File “/usr/local/bin/dcm2bids”, line 8, in

sys.exit(main())

File “/usr/local/lib/python3.10/dist-packages/dcm2bids/dcm2bids.py”, line 244, in main

return app.run()

File “/usr/local/lib/python3.10/dist-packages/dcm2bids/dcm2bids.py”, line 104, in run

self.config.get(“dcm2niixOptions”, DEFAULT.dcm2niixOptions),

AttributeError: ‘list’ object has no attribute ‘get’

v320-001.ls6(935)$ pwd

/scratch/06953/jes6785/NECTARY_DICOMS

As you can see, the run does error out due to an attribute error in the underlying python package. (note that the “ld.so” related error can be ignored, this is created by the xalt module and is irrelevant.) I do not see any error message about the argument though. Could you please verify and let me know if this is the issue? If so, I guess you will need to send this to the developer then.

**Comment by arnaudbore** [comment]
Hi @seaguldee ,

If I recall correctly, this has been fixed in our latest container. Please feel free to reopen an issue if not. 

Thank you
