### ISSUE TITLE
IntendedFor still shows ".gz" when dcm2niix outputs uncompressed files

### ISSUE THREAD

**Issue by azabicki** [UNFmontreal/Dcm2Bids#180]
Hi there, 
thanks for your work and this nice and easy-to-use tool! 

I think I found a bug which prevents the dataset from being validated successfully.
When editing the dcm2niix options to save the data as uncompressed *.nii files (`"dcm2niixOptions": "-b y -ba y -z n -f '%3s_%f_%p_%t'"`) and also using the `"intendedFor": 0` option for fieldmaps, the parsed filename of the `IntendedFor`-Key in the json sidecar of the filemap still points to the _compressed_ *.nii.gz file:
` "IntendedFor": "func/sub-cs_task-pointing_dir-AP_bold.nii.gz"`

Best,
Adam

**Comment by arnaudbore** [comment]
Hi @azabicki ,

This should be fixed now in the master and will be part of the new release 3.0.0
