### ISSUE TITLE
dcm2bids not updating to 2.1.9 (conda environment)

### ISSUE THREAD

**Issue by Catyre** [UNFmontreal/Dcm2Bids#184]
Hello all, 
I am trying to update my dcm2bids version from 2.1.7 to 2.1.9 as this version fixes a bug I have been experiencing with our experiment.  Unfortunately, I have run into some issues:

- Running `pip install --upgrade dcm2bids` in the conda environment (called fMRI) will indeed update dcm2bids to 2.1.9 (confirmed via `pip list`), however proceeding to run dcm2bids in fMRI will output that the version is still 2.1.7.
- Running `conda update dcm2bids` yields the same result
- Making a new conda environment and specifying in the .yml file that dcm2bids should be 2.1.9 loads an environment with 2.1.7, which brings me to the original issue.

I am at a loss of how to proceed.  Any help would be greatly appreciated.

**Comment by SamGuay** [comment]
Hi Catyre,
I think I have identified the problem but to confirm it is that, can you tell us whether the bug you were experiencing is fix when you run the command after you update it? 

It seems that dcm2bids prints 2.1.7 based on [this](https://github.com/UNFmontreal/Dcm2Bids/blob/a129b440235c1e8ce6427bba4858080958072e24/dcm2bids/version.py#L6) even though it's been updated in the environment. 

I've created a new env (with a different name) and I see that version 2.1.9 was installed and seems to be doing the right thing: 
```
sam:~/dcm2bids-proj$ cat environment.yml
name: dcm2bids-fresh
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - dcm2niix
  - dcm2bids
sam:~/dcm2bids-proj$ conda env create --file environment.yml
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages
dcm2niix-1.0.2022072 | 238 KB    | ########################################## | 100%
[...........]
**dcm2bids-2.1.9       | 33 KB     | ########################################## | 100%**
[...........]
ca-certificates-2022 | 150 KB    | ########################################## | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate dcm2bids-fresh
#
# To deactivate an active environment, use
#
#     $ conda deactivate

```

Thanks!

**Comment by Catyre** [comment]
This is the output I get when I run those exact commands.  They seem to differ a fair amount.

<img width="1193" alt="Screen Shot 2022-09-29 at 1 03 18 AM" src="https://user-images.githubusercontent.com/7707850/192943338-5e0e1999-6e2c-4588-b519-26dee2775cc9.png">

**Comment by Catyre** [comment]
Hi Sam, 
Thanks for the reply.  It seems that dcm2bids does indeed update despite outputting v2.1.7, as the problem I was having is now gone.  Thanks for the help!

**Comment by SamGuay** [comment]
Amazing! Sorry about that, I'll make sure to fix this typo in future release! :smile:
