### ISSUE TITLE
dcm2bids very slow on HPC

### ISSUE THREAD

**Issue by hellenmir** [UNFmontreal/Dcm2Bids#186]
Hello, 

I am trying to run the dcm2bids command on an HPC cluster but the command seems to run incredibly slowly (hours and hours) and most of the time does not actually get to completion no matter how much resources I allocate to the job. Looking at the interactive process viewer I can see that the command keeps going into the interruptible sleep mode (S). 
I have also tried to run the same command from the dcm2bids docker container with the singularity shell but it behaves in the same way.

I am new to this so I am wondering if there is anything I am doing wrong.

For reference, I am using the following versions of the packages:
Name                        Version                   Build                      Channel
dcm2bids                  2.1.9                       pyhd8ed1ab_0    conda-forge
dcm2niix                  1.0.20220720         h924138e_0        conda-forge

Thank you for the help!

**Comment by surveybott** [comment]
I had this issue too with a study that had ~100k dicoms per visit. Turned out the network attached storage space the files were on couldn't handle it. Moving the dicoms to a local temporary space ($TMPDIR in most job schedulers) attached to the node solved the issue!

**Comment by arnaudbore** [comment]
From dcm2bids>=3.0.0 we will provide binaries that could also speed up a little bit your conversions on HCP instead of using containers.
