### ISSUE TITLE
Deface not working

### ISSUE THREAD

**Issue by adamnarai** [UNFmontreal/Dcm2Bids#188]
Using the defaceTpl key with pydeface (version 2.0.2) has no effect in the 2.1.7 version and above (works fine in 2.1.6).
No error is shown, it seems like defacing is ignored, the log ends with:
`INFO:dcm2bids.dcm2bids:moving acquisitions into BIDS folder`

**Comment by arnaudbore** [comment]
Will be fixed and generalized in #225 :+1:
