### ISSUE TITLE
citation text

### ISSUE THREAD

**Issue by Arshitha** [UNFmontreal/Dcm2Bids#189]
Hey folks - We've used Dcm2Bids in our curation process and would like to cite the tools we used. Is there a preferred citation text available or is it sufficient to use the GitHub repo link?

**Comment by arnaudbore** [comment]
We are about to submit an abstract to OHBM and later to JOSS. In the meantime you can link to the github repo.
Thank you

**Comment by arnaudbore** [comment]
Here iit is: https://zenodo.org/record/6658099#.Y7wf39KZOiM

**Comment by Arshitha** [comment]
Thank you! Looking forward to seeing y'all at OHBM.
