### ISSUE TITLE
intendedFor field of fmap .json file use \\ separator instead of / 

### ISSUE THREAD

**Issue by guochun-yang** [UNFmontreal/Dcm2Bids#193]
I use the default options to run Dcm2Bids in a windows system, and then copy the BIDS file to a linux system to run fMRIprep. The output of the intendedFor field is something like "func\\sub-..."
However, the fMRIprep simply doesn't recognize the directory unless I manually revise the \\ to /. 
So I'm wondering if there's a simple way to change the separator to / from Dcm2Bids command. 
I guess this may due to the default separator settings of python in windows. Should I use a linux system to do Dcm2Bids instead?
Thanks in advance.

**Comment by arnaudbore** [comment]
Hi @guochun-yang ,

Sorry for the delay but I think you guessed it right, you should be using a linux system to run Dcm2Bids to be then used by fmriprep on a linux system.
