### ISSUE TITLE
Intended For in json files (What's the meaning of 0/1/2)

### ISSUE THREAD

**Issue by colIapse** [UNFmontreal/Dcm2Bids#196]
Dear Developers!

Thanks for your contribution to simplifying the converting progress of dcm2bids!
As a neophyte in the realm of brain imaging technology, the convenience of this app in converting the images to bids have made a profound impression to me.

Recently I have been writing the configure json to successfully finish the conversion.When it turns to fmap,the 'Intended For' parameter has left me some confusion.Would you like to explain how the number '0' '1' '2' refers to one func images  respectively.What's the sequence do they fit the func image?

Like that,in the dcm2bids HOW-TO-GUIDES [https://unfmontreal.github.io/Dcm2Bids/docs/how-to/create-config-file/](url),why the '1'  means it is intended for task-rest_bold，and '2','3' refers to other images respectively
![image](https://user-images.githubusercontent.com/126434134/228483040-060badd3-ac20-4cce-a029-7c0e1f2c3820.png)
Thanks for your time and attention! I really hope can receive your reply

Kind Regards

**Comment by smeisler** [comment]
Answered here (https://neurostars.org/t/intended-for-in-fmap-json-file/25381/2) so feel free to close this issue.
