### ISSUE TITLE
pydra-dcm2bids: Pydra tasks for dcm2bids

### ISSUE THREAD

**Issue by ghisvail** [UNFmontreal/Dcm2Bids#197]
Hello Dcm2Bids developers,

I am a [Pydra](https://pydra.readthedocs.io/en/latest/) developer (successor for Nipype), and I made a Pydra task package for Dcm2Bids to facilitate the build of workflows requiring conversion from DICOM to BIDS. The name for the package is [pydra-dcm2bids](https://pypi.org/project/pydra-dcm2bids/) and calls the `dcm2bids` CLI underneath.

In case there are Pydra users in your community, feel free to point them towards this package. Perhaps a brief mention in your project's README could help? I have used it for a demo to build a workflow to download a DICOM dataset from a PACS, perform BIDS conversion followed by defacing, and it worked great. Feedback and contributions will be warmly welcome :pray: 

Thanks again for working on such a useful conversion tool.

Best regards,
Ghis

**Comment by arnaudbore** [comment]
Hi @ghisvail,

I'm currently working on a new version of dcm2bids that will break the old API.
We really needed to refresh the overall organization of all the files.
It's still in review and we will add some new features as well before releasing v3.0.0  but for the reorganization part you can follow the dev here #200 

Thank you
Arnaud

**Comment by ghisvail** [comment]
Thanks for the heads-up 👍 

I can confirm the necessary version restrictions are in place in `pydra-dcm2bids` to prevent unintended upgrades to the next major release.

Will there be considerable changes to the CLI interface? Or does it concern the library part only?

**Comment by arnaudbore** [comment]
Hi @ghisvail ,

We just release a release candidate of the new version of dcm2bids. 
Here is the new API: https://unfmontreal.github.io/Dcm2Bids/3.0.0rc1/dcm2bids/
Here are some of the major modifications: https://unfmontreal.github.io/Dcm2Bids/3.0.0rc1/upgrade/

Don't hesitate if you have any comments. We plan on releasing 3.0.0 just before OHBM. We will be at OHBM. 
Are you coming ?

**Comment by ghisvail** [comment]
> We just release a release candidate of the new version of dcm2bids.

Congratulations 🎉 

> We will be at OHBM. Are you coming?

Indeed, both to the conference and the brainhack. I'd be happy to chat with you folks 👍

**Comment by arnaudbore** [comment]
If you need any help with this new release don't hesitate. We are still fixing minor issues with 3.0.x
