### ISSUE TITLE
Add "run" info to files even if not duplicates

### ISSUE THREAD

**Issue by smeisler** [UNFmontreal/Dcm2Bids#198]
Hi,

In consideration of BIDS 2.0 proposals (https://docs.google.com/document/d/1LEgsMiisGDe1Gv-hBp1EcLmoz7AlKj6VYULUgDD3Zdw/edit) it may be good to add `run-<run>` labels to all output files, **even if there is only one 1 run.** Let me know if you would like to me to commit a PR for this.

Best,
Steven

**Comment by arnaudbore** [comment]
We are going to wait for the BIDS community to make the move first.
