### ISSUE TITLE
Problem with dcm2bids

### ISSUE THREAD

**Issue by lysianne23** [UNFmontreal/Dcm2Bids#230]
Hi you all, 

I tried using dcm2bids today to convert my data. 
I followed all the steps described in the tutorial, starting w dcm2bids_helper which worked perfectly, then I created my configuration file (attached here as a docx as I can't attach a .json).
[sub-T22_2023-07-12T143517.092028.log](https://github.com/UNFmontreal/Dcm2Bids/files/12031179/sub-T22_2023-07-12T143517.092028.log)

But then when I ran the dcm2bids command as below, it seemed to work and paired files  but did not generate any organized BIDS folder, the outcome is pretty much the same content that what I have with dcm2bids_helper . (attaching the log as well) 

Can you please help me understanding what I'm doing wrong here?
Thanks!

**dcm2bids -d sourcedata/T022/MR5000982517_20230525_123000/scans/ -p T22 -c code/dcm2bids_config.json**

[dcm2bids_config.docx](https://github.com/UNFmontreal/Dcm2Bids/files/12031141/dcm2bids_config.docx)
[sub-T22_2023-07-12T143517.092028.log](https://github.com/UNFmontreal/Dcm2Bids/files/12031180/sub-T22_2023-07-12T143517.092028.log)

**Comment by arnaudbore** [comment]
Hi Lysianne,

Can you run submit your issue on [neurostars](https://neurostars.org/) (with dcm2bids as tag) please ? 
We use github issues mostly for bugs and dev. By submitting on neurostars you also help other users.

Before submitting your issue update your dcm2bids version to 2.1.9.
Thank you
