### ISSUE TITLE
Should this line be pointing to one of the sidecar files? 

### ISSUE THREAD

**Issue by arokem** [UNFmontreal/Dcm2Bids#252]
First of all, love dcm2bids. Thanks for creating it, and thanks for the wonderful documentation!

Second, on this line in the tutorial, we are asked to cat the (at this point, rather empty) config file: 

https://github.com/UNFmontreal/Dcm2Bids/blame/a4eb1d01ab9b292f45bd5610062a0c01cefb96b9/docs/tutorial/first-steps.md#L759

But the output field shows what looks like the contents of one of the json sidecar files. Should this command be pointing to one of the sidecars instead? 

Thanks again!

**Comment by arokem** [comment]
Maybe [this change](https://github.com/UNFmontreal/Dcm2Bids/commit/0e8c576e8ddad02a4acec0f7ea14666ca724d433#diff-77e90629ee3c0de282f9ff84705f39827bd7a80f4f206f0ae40dd432e43a0101L672) should be reverted?

**Comment by arnaudbore** [comment]
Thank you @arokem
