### ISSUE TITLE
Creating several 3D images instead of a single 4D image. 

### ISSUE THREAD

**Issue by granitz** [UNFmontreal/Dcm2Bids#255]
Hello,
I've followed the instructions on https://unfmontreal.github.io/Dcm2Bids/3.0.2/tutorial/first-steps/ on my own data. Specifying the path to DICOM folder: dcm2bids_helper /Dicom/

This produced one compressed nifty file + .json for each task, but it did that for each volume or frame. 

I created a configuration file, taking information just from the first frame for each task, specifying ProtocolName since this can be used to distinguish the different tasks as well as B0 images. 

Then finally, when I run dcm2bids it creates a BIDS folder, but images are again per frame. I'm wondering what I have done wrong so that it correctly collects images for different time points into a single 4D image. 

Kind regards,

**Comment by arnaudbore** [comment]
Dear @granitz,

It could be either a dcm2niix issue or an issue with your dicoms.
Which version of dcm2niix are you using ? Give it a try with the latest version of dcm2niix and check if you still have the same issue.

Best,
Arnaud

**Comment by arnaudbore** [comment]
We can close this issue it seems to be a dcm2niix issue.
