### ISSUE TITLE
Error: Too many NIFTI images with the name 

### ISSUE THREAD

**Issue by CogBrainHealthLab** [UNFmontreal/Dcm2Bids#284]
i think something went wrong with the dcm2niix conversion. For some reason the individual volumes of the fMRI series were not merged together into a single 4D file

`INFO    | --- dcm2bids start ---
INFO    | Running the following command: /home/junhong.yu/dcm2bids/bin/dcm2bids -d /home/junhong.yu/PGMH/sourcedata/GEMH_0004/ -o /home/junhong.yu/PGMH/not_defaced/ -p 0004 -c /home/junhong.yu/PGMH/code/dcm2bids_config.json --auto_extract_entities --force_dcm2bids
INFO    | OS version: Linux-3.10.0-693.el7.x86_64-x86_64-with-centos-7.5.1804-Core
INFO    | Python version: 3.7.10 (default, Jun  4 2021, 06:52:02) [GCC 9.3.0]
INFO    | dcm2bids version: 3.1.1
INFO    | dcm2niix version: v1.0.20230411
INFO    | Checking for software update
INFO    | Currently using the latest version of dcm2bids.
INFO    | Currently using the latest version of dcm2niix.
INFO    | participant: sub-0004
INFO    | config: /home/junhong.yu/PGMH/code/dcm2bids_config.json
INFO    | BIDS directory: /home/junhong.yu/PGMH/not_defaced
INFO    | Auto extract entities: True
INFO    | Validate BIDS: False

INFO    | Running: dcm2niix -b y -ba y -z y -f %3s_%f_%p_%t -o /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004 /home/junhong.yu/PGMH/sourcedata/GEMH_0004
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/016_GEMH_0004_DeIdentified_20220520131925
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/016_GEMH_0004_DeIdentified_20220520131925
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/016_GEMH_0004_DeIdentified_20220520131926
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/016_GEMH_0004_DeIdentified_20220520131926
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/016_GEMH_0004_DeIdentified_20220520131925
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/016_GEMH_0004_DeIdentified_20220520131926
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/016_GEMH_0004_DeIdentified_20220520131926
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/016_GEMH_0004_DeIdentified_20220520131925
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/018_GEMH_0004_DeIdentified_20220520131936
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/018_GEMH_0004_DeIdentified_20220520131937
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/018_GEMH_0004_DeIdentified_20220520131934
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/018_GEMH_0004_DeIdentified_20220520131934
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/018_GEMH_0004_DeIdentified_20220520131937
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/018_GEMH_0004_DeIdentified_20220520131937
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/018_GEMH_0004_DeIdentified_20220520131934
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/018_GEMH_0004_DeIdentified_20220520131936
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/018_GEMH_0004_DeIdentified_20220520131938
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/018_GEMH_0004_DeIdentified_20220520131936
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/018_GEMH_0004_DeIdentified_20220520131934
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/018_GEMH_0004_DeIdentified_20220520131935
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/018_GEMH_0004_DeIdentified_20220520131934
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/018_GEMH_0004_DeIdentified_20220520131935
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/018_GEMH_0004_DeIdentified_20220520131936
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/018_GEMH_0004_DeIdentified_20220520131935
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/018_GEMH_0004_DeIdentified_20220520131936
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/018_GEMH_0004_DeIdentified_20220520131939
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/018_GEMH_0004_DeIdentified_20220520131938
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/018_GEMH_0004_DeIdentified_20220520131938
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/018_GEMH_0004_DeIdentified_20220520131937
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/018_GEMH_0004_DeIdentified_20220520131938
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/009_GEMH_0004_DeIdentified_20220520131819_e2_ph
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/009_GEMH_0004_DeIdentified_20220520131819_e2_ph
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/009_GEMH_0004_DeIdentified_20220520131819_e2_ph
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/009_GEMH_0004_DeIdentified_20220520131819_e2_ph
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/006_GEMH_0004_DeIdentified_20220520131602
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/006_GEMH_0004_DeIdentified_20220520131602
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/006_GEMH_0004_DeIdentified_20220520131602
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/006_GEMH_0004_DeIdentified_20220520131602
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/006_GEMH_0004_DeIdentified_20220520131558
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/006_GEMH_0004_DeIdentified_20220520131558
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/006_GEMH_0004_DeIdentified_20220520131559
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/006_GEMH_0004_DeIdentified_20220520131559
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/006_GEMH_0004_DeIdentified_20220520131558
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/006_GEMH_0004_DeIdentified_20220520131601
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/006_GEMH_0004_DeIdentified_20220520131558
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/006_GEMH_0004_DeIdentified_20220520131601
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/006_GEMH_0004_DeIdentified_20220520131601
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/006_GEMH_0004_DeIdentified_20220520131601
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/006_GEMH_0004_DeIdentified_20220520131557
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/001_GEMH_0004_DeIdentified_20220520131547
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/001_GEMH_0004_DeIdentified_20220520131548
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/001_GEMH_0004_DeIdentified_20220520131548
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/001_GEMH_0004_DeIdentified_20220520131547
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/001_GEMH_0004_DeIdentified_20220520131548
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/001_GEMH_0004_DeIdentified_20220520131547
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/001_GEMH_0004_DeIdentified_20220520131549
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/001_GEMH_0004_DeIdentified_20220520131548
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/001_GEMH_0004_DeIdentified_20220520131549
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/001_GEMH_0004_DeIdentified_20220520131548
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/001_GEMH_0004_DeIdentified_20220520131549
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/001_GEMH_0004_DeIdentified_20220520131547
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/001_GEMH_0004_DeIdentified_20220520131547
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/001_GEMH_0004_DeIdentified_20220520131549
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/001_GEMH_0004_DeIdentified_20220520131549
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/017_GEMH_0004_DeIdentified_20220520131932
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/017_GEMH_0004_DeIdentified_20220520131932
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/017_GEMH_0004_DeIdentified_20220520131932
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/017_GEMH_0004_DeIdentified_20220520131929
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/017_GEMH_0004_DeIdentified_20220520131931
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/017_GEMH_0004_DeIdentified_20220520131929
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/017_GEMH_0004_DeIdentified_20220520131929
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/017_GEMH_0004_DeIdentified_20220520131931
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/017_GEMH_0004_DeIdentified_20220520131931
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/017_GEMH_0004_DeIdentified_20220520131932
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/017_GEMH_0004_DeIdentified_20220520131928
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/017_GEMH_0004_DeIdentified_20220520131928
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/017_GEMH_0004_DeIdentified_20220520131928
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/017_GEMH_0004_DeIdentified_20220520131927
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/017_GEMH_0004_DeIdentified_20220520131928
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/017_GEMH_0004_DeIdentified_20220520131930
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/017_GEMH_0004_DeIdentified_20220520131930
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/017_GEMH_0004_DeIdentified_20220520131930
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/017_GEMH_0004_DeIdentified_20220520131929
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/017_GEMH_0004_DeIdentified_20220520131931
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/017_GEMH_0004_DeIdentified_20220520131930
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/005_GEMH_0004_DeIdentified_20220520131552
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/005_GEMH_0004_DeIdentified_20220520131552
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/005_GEMH_0004_DeIdentified_20220520131552
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/005_GEMH_0004_DeIdentified_20220520131553
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/005_GEMH_0004_DeIdentified_20220520131554
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/005_GEMH_0004_DeIdentified_20220520131553
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/005_GEMH_0004_DeIdentified_20220520131554
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/005_GEMH_0004_DeIdentified_20220520131552
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/005_GEMH_0004_DeIdentified_20220520131552
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/005_GEMH_0004_DeIdentified_20220520131553
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/005_GEMH_0004_DeIdentified_20220520131551
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/005_GEMH_0004_DeIdentified_20220520131556
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/005_GEMH_0004_DeIdentified_20220520131555
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/005_GEMH_0004_DeIdentified_20220520131556
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/005_GEMH_0004_DeIdentified_20220520131556
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/005_GEMH_0004_DeIdentified_20220520131554
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/005_GEMH_0004_DeIdentified_20220520131553
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/005_GEMH_0004_DeIdentified_20220520131551
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/005_GEMH_0004_DeIdentified_20220520131554
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/005_GEMH_0004_DeIdentified_20220520131553
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/005_GEMH_0004_DeIdentified_20220520131556
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/005_GEMH_0004_DeIdentified_20220520131555
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/005_GEMH_0004_DeIdentified_20220520131555
Error: Too many NIFTI images with the name /home/junhong.yu/PGMH/not_defaced/tmp_dcm2bids/sub-0004/005_GEMH_0004_DeIdentified_20220520131555
Error: Converted 2330 of 2440 files
`

**Comment by arnaudbore** [comment]
Dear @CogBrainHealthLab ,

I suggest you to submit this question on [neurostars](https://neurostars.org/) with the tags dcm2niix and dcm2bids. 
Since it's a dcm2niix issue and it could be useful for other users, it will make more sense to raise this issue on [neurostars](https://neurostars.org/)

Best,
Arnaud
