### ISSUE TITLE
compKeys default for run numbering doesn't seem like a good one

### ISSUE THREAD

**Issue by ericearl** [UNFmontreal/Dcm2Bids#288]
The [`compKeys` advanced configuration option](https://unfmontreal.github.io/Dcm2Bids/3.1.1/how-to/use-advanced-commands/#compkeys) is defaulted to providing run numbering based first on `SeriesNumber`, then on `AcquisitionTime`, then on `SidecarFilename`. I don't think this is a good default.

I tested a few different scenarios with an old version of dcm2bids (v2.1.4) and a newer version of dcm2bids (v3.1.0). I had 6 ABCD Study subject's sessions, 2 from each of the 3 scanners in the study (GE, Philips, and Siemens). I converted each and checked the run ordering provided by dcm2bids against the actual acquisition times as stored in the BIDS sidecar JSONs. Even with v3.1.0, using the `compKeys` default, it got the run ordering wrong. When I provided the `compKeys` argument for the v3.1.0, it worked as desired and correctly ordered all runs for all 6 sessions.

I can't imagine a situation where the default run order shouldn't be sorted by `AcquisitionTime`, so this issue is to simply propose you change the default in the future. I will use the `compKeys` option for ABCD Study data until then.

Current:

```json
"compKeys": ["SeriesNumber", "AcquisitionTime", "SidecarFilename"]
```

Desired:

```json
"compKeys": ["AcquisitionTime", "SeriesNumber", "SidecarFilename"]
```

**Comment by arnaudbore** [comment]
Thank you @ericearl 
This has been fixed in the master and will be available in the next release :+1:
