### ISSUE TITLE
Allowing for post_op command's output to be printed to stdout

### ISSUE THREAD

**Issue by joey-scanga** [UNFmontreal/Dcm2Bids#294]
Hello! 

For my use case, it would be very useful if the output of the command specified in post_op could be printed out to stdout by triggering an option, perhaps something like `--print_post_op`. I'm happy to work on this, I already have the enhancement nearly complete on my own fork of the repo, just need to write some tests.

**Comment by arnaudbore** [comment]
Hello @joey-scanga,
It would be nice I think to get this information in the log more than getting it in sdout so we don't have to trigger it and always save it in the log file.
Go ahead don't hesitate to submit a PR.
Thank you in advance

**Comment by arnaudbore** [comment]
This have been fixed and it's now part of the dev branch. We need to update the documentation and then it will be part of our next release.
