### ISSUE TITLE
Support for MRS data?

### ISSUE THREAD

**Issue by juliam98** [UNFmontreal/Dcm2Bids#319]
Does the package support mrs files? I find that when I run `dcm2bids` it completely ignores mrs files. They are not in the temporary directory, so the issue isn't that they weren't matched. 

If possible could you add this funciton? I have tried using `spec2nii` for conversion to .nii and generating sidecar files, but the sidecars it generates are only a couple lines, and wouldn't even be enough information to use with `dcm2bids` as there are no differences in tags between different mrs data. I've been trying to write my own script to get full sidecar data for my mrs files, but only suceeded with half of my data (the other was after scanner software update :| )

I don't feel competent enough to contribute directly to your package but if I can help in any way let me know. You can see what I have managed to accomplish with sidecar files for mrs data [here](https://github.com/juliam98/siemens-dicom-tags). You can also find examples of dicom mrs data there.

**Comment by arnaudbore** [comment]
Hello @juliam98 ,
dcm2bids ignores mrs files because dcm2niix does not convert them.
There is nothing dcm2bids can do here.

Your best shot is to get help from spec2nii people to extract more information into the json files.
Once you'll get everything needed, dcm2bids will do its job.

Hope it helps,
Arnaud

**Comment by marcelzwiers** [comment]
I stumbled on this post and I don't want to promote bidscoin over here, but if it may be of any help, this spec2nii plugin is doing what you were asking:

https://bidscoin.readthedocs.io/en/latest/plugins.html#spec2nii2bids-a-plugin-for-mr-spectroscopy-data
