### ISSUE TITLE
Exclusion criteria

### ISSUE THREAD

**Issue by neurolabusc** [UNFmontreal/Dcm2Bids#36]
Is it possible to have a criteria that helps exclude an image. For example, for our DWI routines we want to convert the raw data to BIDS, but exclude the console-generated derived Trace/FA maps. For our Siemens hardware, the derived images have almost identical BIDS tags to the raw data, but we can ignore them if we can exclude files with "ImageType": "*DERIVED*". 

For this specific case I realize I can also modify your script:
  self.options = "-b y -ba y -z y -f '%3s_%f_%p_%t'"
to read
  self.options = "-i y -b y -ba y -z y -f '%3s_%f_%p_%t'"

But there are other cases where this would help (for example, GE and Philips tend not to label their derived images in the ImageType tag).

```
        {
            "dataType": "dwi",
            "modalityLabel": "dwi",
            "criteria": {
                "SequenceVariant": "SK_SS"
            }
            "exclude": {
                "ImageType": "*DERIVED*"
            }
        }

```

**Comment by arnaudbore** [comment]
Dear @neurolabusc,

I know it's been 2 years since you wrote this message without any response. I'm deeply sorry about that. 
From your point of view, is this issue still relevant ?

We are starting a 2021 initiative to push dcm2bids forward.
Please don't hesitate to answer to our survey following this [initiative](https://github.com/UNFmontreal/Dcm2Bids/issues/108)

Have a good day
Arnaud

**Comment by neurolabusc** [comment]
For my own work, I just use `-i y`, so I will close this issue. Others with similar requests can create their own issue, so I am closing this one.

**Comment by JoTisch** [comment]
How can you pass the `-i y` flag from dcm2bids to dcm2niix? Or more general: how can you set dcm2niix flags while operating with dcm2bids?

**Comment by tletut0ur** [comment]
Sorry if this is a late answer. In version 3.2.0, I was able to pass the `-i y` flag by adding it to the `dcm2niixOptions` variable in the `dcm2bids/utils/utils.py`. I don't think it is a clean way to do it and would love for `dcm2bids` to have `dcm2niixOptions` exposed somewhere in the CLI, even if it stays to the current default for most users. I can prepare a PR if needed.

Edit: Just figured out the `dcm2niixOptions` can be set from the configuration json. Apologies.
