### ISSUE TITLE
4D GE spin echo field maps: AP/PA both in one NIfTI

### ISSUE THREAD

**Issue by ericearl** [UNFmontreal/Dcm2Bids#37]
Hi,

We at OHSU in Portland, OR, USA, are trying to process ABCD Study data from GE scanners and the two 3D volumes of forward (posterior-anterior) & reverse (anterior-posterior), aka. parallel & anti-parallel, phase encode direction GE spin echo field maps are concatenated in the 4th dimension so they are always an (X-by-Y-by-Z-by-2) 4D volume (I think this is what GE NIfTI's always do with spin echo field maps).

Dcm2Bids only produces one NIfTI and one JSON sidecar, even though the NIfTI's should split on the 4th dimension into two separate 3D volumes whose PhaseEncodingDirection JSON sidecar field should be `<i, j, or k>` and `<i, j, or k>-`.

We have a hacky workaround for this right now which involves us splitting the NIfTI and copying the sidecar JSON into two sidecar JSON's, one for each volume, then re-labeling the incorrect PhaseEncodingDirection in one of them.

Anyway, let me know if I can provide any more help to get this resolved.

~Eric

**Comment by carlosivanr** [comment]
Hi Eric,
Thanks for writing this up as it sheds light into something I'm running into. I used the abcd2bids.py tool to convert abcd fast track data to bids format for pre-processing. I noticed that a handful of the participants in my data set did not get their fieldmaps converted from dicom to to nifti, and were not placed in the final abcd2bids.py output directory. The commonality among all but one of them was that their data came off of a GE scanner. I'm interested in manually converting their fieldmaps, using Dcm2Bids, but how do you know which of the 3d volumes is in the <i, j, k> and which one is in the <i, j, or k>- ? Is there a default for the abcd study participants from GE scanners? Any insight on this would be greatly appreciated.
Best,
Carlos

**Comment by neurolabusc** [comment]
I believe this issue is described [here](https://github.com/rordenlab/dcm2niix/issues/245) as well as [here](https://neurostars.org/t/abcd-ge-data-and-phase-encoding/4972). Specifically, the ABCD team did not use the GE software to export DICOMs. Rather they generated their own DICOM images. I presume this is because at the time the GE systems could not reconstruct multi-band data direct to DICOM. When I looked at this, the images were very atypical. This is not an issue with dcm2niix or Dcm2Bids. Rather, the images themselves do not have the expected meta data. I would contact the ABCD team directly for support, perhaps @HaukeBartsch can provide insight.

**Comment by carlosivanr** [comment]
> I believe this issue is described [here](https://github.com/rordenlab/dcm2niix/issues/245) as well as [here](https://neurostars.org/t/abcd-ge-data-and-phase-encoding/4972). Specifically, the ABCD team did not use the GE software to export DICOMs. Rather they generated their own DICOM images. I presume this is because at the time the GE systems could not reconstruct multi-band data direct to DICOM. When I looked at this, the images were very atypical. This is not an issue with dcm2niix or Dcm2Bids. Rather, the images themselves do not have the expected meta data. I would contact the ABCD team directly for support, perhaps @HaukeBartsch can provide insight.

Thank you Chris. That helps a lot.

Best,
Carlos
