### ISSUE TITLE
Add regex examples in the documentation

### ISSUE THREAD

**Issue by cbedetti** [UNFmontreal/Dcm2Bids#45]
It's possible to be more flexible with `"searchMethod": "re"`

Put example in the documentation to do thing like :

- "EchoTime": > 0.1
- "SeriesDescription": "MPRAGE" or "IR-FSPGR"

**Comment by arnaudbore** [comment]
I tried using `re` and the "EchoTime": > 0.1 but get a json error: 
`json.decoder.JSONDecodeError: Expecting value: line 39 column 27 (char 1041)`

Can you give a quick example here ?
Thank you

**Comment by arnaudbore** [comment]
Documentation is continuously being updated so it's not an issue here. 
BTW:
`"EchoTime": > 0.1` is not possible with re
