### ISSUE TITLE
Update BIDSversion in dataset_description?

### ISSUE THREAD

**Issue by jcohenadad** [UNFmontreal/Dcm2Bids#46]
Currently, the [hard-coded version for BIDSversion flag in dataset_description.json](https://github.com/cbedetti/Dcm2Bids/blob/master/scripts/dcm2bids_scaffold#L36) is 1.0.2. Should we update it to [current BIDS version](https://bids-specification.readthedocs.io/en/stable/) (1.2.0)?

Note: this will likely evolve in time, meaning: maintenance load from dcm2bids developer side. A maintenance strategy to minimize workload should be considered.

**Comment by cbedetti** [comment]
I have some tools to fetch last release version on a github repo in `version.py`.
Do you know a place to fetch this version number ?

**Comment by jcohenadad** [comment]
I'm not sure what is the best strategy here, because ultimately the sidecar json files are generated by dcm2niix, so what we should be fetching is the BIDS version that the current dcm2niix is aiming to.

ideally, dcm2niix would return the BIDS version it is compatible with. Maybe @neurolabusc has some input?

**Comment by cbedetti** [comment]
I have update the BIDS version manually for now.

**Comment by arnaudbore** [comment]
@jcohenadad seems to me that BIDS version is very ambiguous since people can output almost everything they want from dcm2bids. If you agree, I would remove completely the version and people are free to put whatever they want but neither dcm2niix or dcm2bids can validate at this point the exact BIDS version they follow.

**Comment by jcohenadad** [comment]
> @jcohenadad seems to me that BIDS version is very ambiguous since people can output almost everything they want from dcm2bids. If you agree, I would remove completely the version and people are free to put whatever they want but neither dcm2niix or dcm2bids can validate at this point the exact BIDS version they follow.

@agahkarakuzu what do you think?

**Comment by agahkarakuzu** [comment]
@jcohenadad the bids version would be more of an issue for bids validator and I think there is value in specifying the version which is followed by the dataset. The version validity span is probably wider for methods like bold and dwi, in that case, but even they are going to undergo some changes from 2.0 on. I hope that converters will align their outputs with versions at some point though.

**Comment by jcohenadad** [comment]
hum... based on @agahkarakuzu comment I would keep the field then, at least to make sure we can be cross-compatible with previous BIDS versions. Eg in 2y from now it is anticipated that BIDS convention will change, therefore so will dcm2bids, and we want users to be able to know what BIDS-compatible version `dcm2bids` will deliver. So, regardless of what `dcm2niix` is doing, we can just _aim_ at following the "present time" BIDS convention and thus encode its version (today being v1.4.1, no more v1.2.0 as in my original post https://github.com/UNFmontreal/Dcm2Bids/issues/46#issue-428800960 😅 )

also: the link in my original post is broken-- here is the correct one: https://github.com/UNFmontreal/Dcm2Bids/blob/38f803f4b7f74eea2c350e2a16589b6c804d2afe/dcm2bids/scaffold/dataset_description.json#L3

**Comment by arnaudbore** [comment]
Now using `DEFAULT.bids_version`
