### ISSUE TITLE
dcm2bids - several customLabels?

### ISSUE THREAD

**Issue by jbruegge** [UNFmontreal/Dcm2Bids#70]
Hi there,

I have been trying to find out whether or not it is possible to have several customLabels (since it's plural I would have thought that it is possible), however I cannot find anything confirming or denying this assumption.
So is it possible? If yes, how do you specify them?

Thanks in advance!
Cheers
Julia

**Comment by dlevitas** [comment]
Hi Julia,

If you're suggesting something like this
```
         "dataType": "func",
         "modalityLabel": "bold",
         "customLabels": "task-bart",
         "customLabels": "run-01",
         "criteria": {
            "SidecarFilename": "006*"
         },
         "sidecarChanges": {
            "TaskName": "bart"
         }
      },

then it's only going to use the last ```customLabels``` key for the conversion, which I assume isn't want you want. Using the example above, the file name in the ```func``` directory would be ```sub-01_run-01_bold.nii.gz```

That being said, you can add more to the ```customLabels``` field using the ```_``` separator. So having this
```
      {
         "dataType": "func",
         "modalityLabel": "bold",
         "customLabels": "task-std_run-01",
         "criteria": {
            "SidecarFilename": "006*"
         },
         "sidecarChanges": {
            "TaskName": "bart"
         }
      },
```
would produce a file name with more information: ```sub-01_task-bart_run-01_bold.json```

Hope this helps.

Dan

**Comment by jbruegge** [comment]
Hi Dan,

yes, that helps indeed, thank you very much! :)

Cheers,
Julia
