### ISSUE TITLE
json decoder issue

### ISSUE THREAD

**Issue by mosugo414** [UNFmontreal/Dcm2Bids#71]
I am trying to follow this tutorial (https://cbedetti.github.io/Dcm2Bids/tutorial/) using anaconda 3.7 

I run dcm2bids using the terminal, and I get the following error about the anaconda environment file, which is located at /.conda/envs/dcm2bids/lib/python3.7/json/decoder.py:

"json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 11 column 9 (char 223)"

The text of the file in question looks like this to line 27:

"""Implementation of JSONDecoder
"""
import re

from json import scanner
try:
    from _json import scanstring as c_scanstring
except ImportError:
    c_scanstring = "None"

__all__ = ['JSONDecoder', 'JSONDecodeError']

FLAGS = re.VERBOSE | re.MULTILINE | re.DOTALL

NaN = float('nan')
PosInf = float('inf')
NegInf = float('-inf')

class JSONDecodeError(ValueError):
    """Subclass of ValueError with the following additional properties:

    msg: The unformatted error message
    doc: The JSON document being parsed
    pos: The start index of doc where parsing failed
    lineno: The line corresponding to pos
    colno: The column corresponding to pos"

I have tried changing the single quotes to double quotes, but this does not help. Does anyone have any advice on how to proceed?

**Comment by dlevitas** [comment]
Hi @mosugo414,

What is the dcm2bids command you're using, and what does your configuration file look like?

**Comment by ctsmith94** [comment]
Hello,


I am having the same issue. When I try to run dcm2bids on a subject, I get the same error. Terminal shows the following:

(base) MacBook-Air:~ epsg4$ dcm2bids -d /Users/epsg4/sourcedata/CM_MTR_Subject_DICOM/sub-ccos01/DICOM  -p sub-ccos01 -c code/dcm2bids_config.json
Traceback (most recent call last):
  File "/opt/miniconda3/bin/dcm2bids", line 114, in <module>
    sys.exit(main())
  File "/opt/miniconda3/bin/dcm2bids", line 109, in main
    app = Dcm2bids(**vars(args))
  File "/opt/miniconda3/lib/python3.7/site-packages/dcm2bids/dcm2bids.py", line 48, in __init__
    self.config = load_json(config)
  File "/opt/miniconda3/lib/python3.7/site-packages/dcm2bids/utils.py", line 53, in load_json
    data = json.load(f, object_pairs_hook=OrderedDict)
  File "/opt/miniconda3/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/opt/miniconda3/lib/python3.7/json/__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "/opt/miniconda3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/miniconda3/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 20 column 11 (char 458)

Config file reads as follows: 
{
    "descriptions": [
        {
            "dataType": "anat",
            "modalityLabel": "T1w",
            "criteria": {
                "SidecarFilename": "006*"
            }
        },
        {
            "dataType": "anat",
            "modalityLabel": "T2w",
            "criteria": {
                "SidecarFilename": "007*"
            }
        },
        {
          "dataType": "anat",
          "modalityLabel": "acq-MTon_MTS"
          "criteria": {
              "SidecarFilename": "002*"
          }
        },
        {
          "dataType": "anat",
          "modalityLabel": "acq-MToff_MTS"
          "criteria": {
              "SidecarFilename": "003*"
          }
I have also tried changing the single quotes to double quotes as mentioned above. Any help would be appreciated. Thank you.

**Comment by arnaudbore** [comment]
> Hello,
> 
> I am having the same issue. When I try to run dcm2bids on a subject, I get the same error. Terminal shows the following:
> 
> (base) MacBook-Air:~ epsg4$ dcm2bids -d /Users/epsg4/sourcedata/CM_MTR_Subject_DICOM/sub-ccos01/DICOM -p sub-ccos01 -c code/dcm2bids_config.json
> Traceback (most recent call last):
> File "/opt/miniconda3/bin/dcm2bids", line 114, in
> sys.exit(main())
> File "/opt/miniconda3/bin/dcm2bids", line 109, in main
> app = Dcm2bids(**vars(args))
> File "/opt/miniconda3/lib/python3.7/site-packages/dcm2bids/dcm2bids.py", line 48, in **init**
> self.config = load_json(config)
> File "/opt/miniconda3/lib/python3.7/site-packages/dcm2bids/utils.py", line 53, in load_json
> data = json.load(f, object_pairs_hook=OrderedDict)
> File "/opt/miniconda3/lib/python3.7/json/**init**.py", line 296, in load
> parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
> File "/opt/miniconda3/lib/python3.7/json/**init**.py", line 361, in loads
> return cls(**kw).decode(s)
> File "/opt/miniconda3/lib/python3.7/json/decoder.py", line 337, in decode
> obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> File "/opt/miniconda3/lib/python3.7/json/decoder.py", line 353, in raw_decode
> obj, end = self.scan_once(s, idx)
> json.decoder.JSONDecodeError: Expecting ',' delimiter: line 20 column 11 (char 458)
> 
> Config file reads as follows:
> {
> "descriptions": [
> {
> "dataType": "anat",
> "modalityLabel": "T1w",
> "criteria": {
> "SidecarFilename": "006*"
> }
> },
> {
> "dataType": "anat",
> "modalityLabel": "T2w",
> "criteria": {
> "SidecarFilename": "007*"
> }
> },
> {
> "dataType": "anat",
> "modalityLabel": "acq-MTon_MTS"
> "criteria": {
> "SidecarFilename": "002*"
> }
> },
> {
> "dataType": "anat",
> "modalityLabel": "acq-MToff_MTS"
> "criteria": {
> "SidecarFilename": "003*"
> }
> I have also tried changing the single quotes to double quotes as mentioned above. Any help would be appreciated. Thank you.

You've got a missing comma after each: `"acq-MTon_MTS"`

**Comment by arnaudbore** [comment]
@mosugo414  can you share with us your config file.
json.decoder.JSONDecodeError means your config file is not formatted correctly.

**Comment by ctsmith94** [comment]
> > Hello,
> > I am having the same issue. When I try to run dcm2bids on a subject, I get the same error. Terminal shows the following:
> > (base) MacBook-Air:~ epsg4$ dcm2bids -d /Users/epsg4/sourcedata/CM_MTR_Subject_DICOM/sub-ccos01/DICOM -p sub-ccos01 -c code/dcm2bids_config.json
> > Traceback (most recent call last):
> > File "/opt/miniconda3/bin/dcm2bids", line 114, in
> > sys.exit(main())
> > File "/opt/miniconda3/bin/dcm2bids", line 109, in main
> > app = Dcm2bids(**vars(args))
> > File "/opt/miniconda3/lib/python3.7/site-packages/dcm2bids/dcm2bids.py", line 48, in **init**
> > self.config = load_json(config)
> > File "/opt/miniconda3/lib/python3.7/site-packages/dcm2bids/utils.py", line 53, in load_json
> > data = json.load(f, object_pairs_hook=OrderedDict)
> > File "/opt/miniconda3/lib/python3.7/json/**init**.py", line 296, in load
> > parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
> > File "/opt/miniconda3/lib/python3.7/json/**init**.py", line 361, in loads
> > return cls(**kw).decode(s)
> > File "/opt/miniconda3/lib/python3.7/json/decoder.py", line 337, in decode
> > obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> > File "/opt/miniconda3/lib/python3.7/json/decoder.py", line 353, in raw_decode
> > obj, end = self.scan_once(s, idx)
> > json.decoder.JSONDecodeError: Expecting ',' delimiter: line 20 column 11 (char 458)
> > Config file reads as follows:
> > {
> > "descriptions": [
> > {
> > "dataType": "anat",
> > "modalityLabel": "T1w",
> > "criteria": {
> > "SidecarFilename": "006*"
> > }
> > },
> > {
> > "dataType": "anat",
> > "modalityLabel": "T2w",
> > "criteria": {
> > "SidecarFilename": "007*"
> > }
> > },
> > {
> > "dataType": "anat",
> > "modalityLabel": "acq-MTon_MTS"
> > "criteria": {
> > "SidecarFilename": "002*"
> > }
> > },
> > {
> > "dataType": "anat",
> > "modalityLabel": "acq-MToff_MTS"
> > "criteria": {
> > "SidecarFilename": "003*"
> > }
> > I have also tried changing the single quotes to double quotes as mentioned above. Any help would be appreciated. Thank you.
> 
> You've got a missing comma after each: `"acq-MTon_MTS"`

Thank you. Changed the file to add the commas and close brackets per the example at https://unfmontreal.github.io/Dcm2Bids/config/  to the following:
{
    "descriptions": [
        {
            "dataType": "anat",
            "modalityLabel": "T1w",
            "criteria": {
                "SidecarFilename": "006*"
            }
        },
        {
            "dataType": "anat",
            "modalityLabel": "T2w",
            "criteria": {
                "SidecarFilename": "007*"
            }
        },
        {
          "dataType": "anat",
          "modalityLabel": "acq-MTon_MTS",
          "criteria": {
              "SidecarFilename": "002*"
          }
        },
        {
          "dataType": "anat",
          "modalityLabel": "acq-MToff_MTS",
          "criteria": {
              "SidecarFilename": "003*"
            }
        ]
    }

but now gives the following error: 
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 30 column 9 (char 706)

**Comment by arnaudbore** [comment]
@ctsmith94 check the error it gaves you. Line 30 you've got an issue. 
It doesn't understand why you have a bracket there.

**Comment by ctsmith94** [comment]
@arnaudbore How do I end the config file to let json.decoder understand that it is the end? The error prompts are directing me to keep adding data types but I want it to end after  "SidecarFilename": "003*"
Thank you.

**Comment by arnaudbore** [comment]
@ctsmith94 Check when you open an accolade { and when you close it. 
At the very end, you end up by closing the bloc description and the json file.
In other words, It should end with ] }

**Comment by arnaudbore** [comment]
You can also validate your json file using this website: https://jsonlint.com/

**Comment by dlevitas** [comment]
Hi,

I just wanted to jump in because I noticed another issue with the config file. Your `acq` labels contain an underscore (e.g `acq-MTon_MTS`), which isn't BIDS valid and will cause your dataset to fail validation. The reason is because the underscore is specifically meant to separate entities in the file names (e.g. `sub_1000_ses-01_run-1_bold.nii.gz`). What you can do instead is `acq-MTonMTS`

Also, `acq-MTon_MTS` needs to go in the `cusomLabels` field, not `ModalityLabel`

**Comment by ctsmith94** [comment]
@dlevitas @arnaudbore thank you both!

**Comment by arnaudbore** [comment]
We are starting a [2021 initiative](https://github.com/UNFmontreal/Dcm2Bids/issues/108).
It would be awesome if you can share with us your thoughts on dcm2bids and if you want to be involved (everybody can help) that would be a good time.
