### ISSUE TITLE
Problems setting .config file

### ISSUE THREAD

**Issue by anarfouto** [UNFmontreal/Dcm2Bids#87]
Hi!

1. I am struggling with some issues while trying to set up the config. file. Firstly, I tested with the example dataset and I did not have any problems. My sourcedata only contains two image datasets: asl and bold fmri. This is the procedure I am following:

- dcm2bids_helper -d sourcedata/;
-  dcm2bids -d sourcedata/ -p 01 -c code/config.json

I am using the SeriesDescription as a criterion:
"SeriesDescription": "ep2d_bold_nback_moco_p2_s3_prescan",

This is how I set up the .config file ignoring the asl data:
{
    "searchMethod": "fnmatch",
    "defaceTpl": "pydeface --outfile {dstFile} {srcFile}",
    "descriptions": [
        {
            "dataType": "func",
            "modalityLabel": "bold",
            "customLabels": "task-nback",
            "criteria": {
                "SeriesDescription": "ep2d_bold_nback*"
            }
        }
    ]
}

However, my data remains in the tmp file. Can anyone help me spot what I am doing wrong? I already did several attempts to solve the problem, but without success.

2. Is it possible to change the arguments passed to dcm2niix while using dcm2bids) For example:
**default:** dcm2niix -b y -ba y -z y -f '%3s_%f_%p_%t' -o /dir/
**replace with:** dcm2niix -b y -f %d_%s  -o /dir/

Thank you in advance for your help!

**Comment by arnaudbore** [comment]
@anaf9, sorry for the long delay. Does this issue still remain ?

**Comment by arnaudbore** [comment]
Dear @anaf9,

Don't hesitate to reach out to us if you still have this issue. 
Also, you can join us to our [2021 initiative](https://github.com/UNFmontreal/Dcm2Bids/issues/108)

Have a good day
Arnaud

**Comment by arnaudbore** [comment]
I'm closing this PR.
Documentation about dcm2niix options: [dcm2niix](https://unfmontreal.github.io/Dcm2Bids/docs/how-to/use-advanced-commands/#dcm2niixoptions)
If you need some help don't hesitate to post on [Neurostars](https://neurostars.org/) with the tag dcm2bids
