### ISSUE TITLE
py38 compatibility issue: No module named ‘dcm2bids.scaffold’

### ISSUE THREAD

**Issue by SaharSaba** [UNFmontreal/Dcm2Bids#89]
Hi,
After the installation of dcm2bids, I see this error. could you please help me to solve this issue? Thanks 

dcm2bids -d ‘/home/sahar/DICOM/img’ -p sub-teh -c ~/Desktop/config_spine.txt -o teh_spineGeneric
Traceback (most recent call last):
File “/home/sahar/.local/bin/dcm2bids”, line 5, in
from dcm2bids.dcm2bids import main
File “/home/sahar/.local/lib/python3.8/site-packages/dcm2bids/init.py”, line 12, in
from .scaffold import scaffold
ModuleNotFoundError: No module named ‘dcm2bids.scaffold’

**Comment by SaharSaba** [comment]
Also, I followed the #76 issue, but it did not work well for me

**Comment by jcohenadad** [comment]
@SaharSaba thank you for reporting this issue. dcm2bids is currently not tested on py38. Could you please try with py37 and let us know how it goes? If this is indeed a py38-specific problem, we will make sure to address it.

**Comment by SaharSaba** [comment]
Yes, dcm2bids is not compatible with py3.8. I downgrade it to py3.7
Thanks.

**Comment by jcohenadad** [comment]
i renamed the issue to be more explicit-- we will fix py38 compat (and py39 with has just been released 😅 )

**Comment by SaharSaba** [comment]
Great. Thanks.

**Comment by arnaudbore** [comment]
@SaharSaba I manage to make dcm2bids working with python 3.8.0 using: `pip install -e .` within dcm2bids folder.
Can you tell me if it works that way ?

**Comment by arnaudbore** [comment]
@SaharSaba dcm2bids is now compatible with python3.8 and python3.9 using `pip install  dcm2bids`

If you are interested, you can also join us to our [2021 initiative](https://github.com/UNFmontreal/Dcm2Bids/issues/108)
