### ISSUE TITLE
dcm2niix version pinning is in the wrong place

### ISSUE THREAD

**Issue by kousu** [UNFmontreal/Dcm2Bids#92]
https://github.com/UNFmontreal/Dcm2Bids/blob/892c51e6671a1ddf3513381d8ecf082d9b400862/dcm2bids/utils.py#L31

This should be handled by a package manager, not buried inside of `utils.py`. I think I understand what guided this: dcm2niix isn't a python app, so it can't be versioned with python mechanisms. I get that. But this isn't a good place to handle it!

In its place we should:
- put a note in the README about the supported dcm2niix version(s)
- we can write a brew tap for dcm2bids that declares the correct dependency
- write a conda-forge recipe for dcm2bids that declares the correct dependency

that'll handle most platforms our users are on, and for others they can follow the README and figure it out for themselves.

**Comment by arnaudbore** [comment]
dcm2niix is mandatory but any version will work great depending on your config file. We don't even use this variable. We just check if the user is not using the latest dcm2niix version. That's all.
