### ISSUE TITLE
'import' not 'move'?

### ISSUE THREAD

**Issue by kousu** [UNFmontreal/Dcm2Bids#98]
https://github.com/UNFmontreal/Dcm2Bids/blob/14ff8b1443010ab88ca32645c38cdc71c42499db/dcm2bids/dcm2bids.py#L145

has a bunch of cases, all of which essentially do

https://github.com/UNFmontreal/Dcm2Bids/blob/14ff8b1443010ab88ca32645c38cdc71c42499db/dcm2bids/dcm2bids.py#L189

I think this is somewhat bug-prone. This is meant to operate on the `tmp_dcm2bids/` folder but if it's accidentally pointed elsewhere it could really wreck your dataset. I think it's a lot safer to use `os.copy` and/or piping through filters; never touch your source data, even if it's intermediate data.

**Comment by kousu** [comment]
I see in the docs that this was probably motivated by wanting to leave the unmatched files available for inspection. That could be handled in this paradigm too: just copy the unmatched files to an "unmatched" folder.

**Comment by bwagnerwork** [comment]
Why would one want to keep intermediate files and/or create more duplication?  Also, if moved to an "unmatched" what happens on a rerun, for example after updating a rule for a new variation.

**Comment by kousu** [comment]
Yeah, it's exactly because I'm thinking about re-runs! A BIDS dir made out of mixtures of runs of dcm2bids is a buggy BIDS dir because stateful programming is extremely fragile. Each run should insist on being given a fresh directory to work in. In fact, maybe it should generate its own fresh directory.

Personally, I wouldn't even preserve the intermediate files. I would skip generating `tmp_dcm2bids/` entirely, just copying files directly out of the source dir, and I would replace having "leftover" files for users to examine with writing a note to the log about them.

Does that clarify my thinking?

**Comment by arnaudbore** [comment]
Maybe not a good habit but I've been using the `tmp_dmc2bids` and the ability to re-run dcm2bids a lot. 
I work a lot with multi-sites projects where simple modalities are easy to catch across vendors. So I run dcm2bids with a single config file to catch T1s for example, and then I would use a per vendor config files to catch everything else without having to convert again dcm->niix.

**Comment by bwagnerwork** [comment]
I misunderstood.  Thought you wanted to keep tmp_dcm2bids and do an unmatched.  I think my preference would be to leave tmp_dcm2bids. Or an option to select between tmp_dcm2bids or an unmatched directory.

**Comment by kousu** [comment]
> Maybe not a good habit but I've been using the `tmp_dmc2bids` and the ability to re-run dcm2bids a lot.
> I work a lot with multi-sites projects where simple modalities are easy to catch across vendors. So I run dcm2bids with a single config file to catch T1s for example, and then I would use a per vendor config files to catch everything else without having to convert again dcm->niix.

Oh I see. You want to be able to run multiple operations on the same or multiple source datasets to produce a single final dataset. This makes total sense! So scratch what I said about insisting on an empty target directory. That was wrong!

Some of my confusion I want to offload onto sub-issue #100. `tmp_dcm2bids/` confuses me but we can talk about that over there. Here, I still think the idea of importing instead of moving is a valuable way to think about the process. The process already works as an import 99% of the time, because 99% of the time you have a single dataset which is _initially copied into `tmp_dcm2bids/` by `dcm2niix` and from there is sorted.

But I still think you should be able to do multiple datasets and, like @arnaudbore mentions, use multiple configs, without fear, e.g.:

```
dcm2bids -d ~/database/bk_ij99 -c scrape_anat.json -p 01 -o dataset/
dcm2bids -d ~/database/bk_ij99  -c t1.json -p 02 -o dataset/
dcm2bids -d /mnt/terabittles/vapourouset-alphaghetti/d1 -c siemens_tidy1.json -p 01b -o dataset/
```

A big part of making that reliable, is making sure files are copied directly from the `-d` to the `-o` path. Going via `dcm2niix` is fragile; that's kind of the core of my issue in #100).

That means getting rid of every [`rename(3)`](https://linux.die.net/man/3/rename) call whether it's directly in our code or not.

I _think_ that just means going over

https://github.com/UNFmontreal/Dcm2Bids/blob/14ff8b1443010ab88ca32645c38cdc71c42499db/dcm2bids/dcm2bids.py#L145-L189

with a comb, and also changing the source of all the paths in that block to point at the source given to `Dcm2bids()`.

**Comment by arnaudbore** [comment]
This has been fixed.
