### ISSUE TITLE
Overlapping criteria

### ISSUE THREAD

**Issue by kousu** [UNFmontreal/Dcm2Bids#99]
It's possible for the sets of sidecars covered by each criteria to overlap, for example `"SidecarFilename": "*MPRAGE*"` and `"Modality": "M*"` intersect on [the example anat-scan](https://github.com/UNFmontreal/Dcm2Bids/blob/81de8ad803c4c56614a43c64b86afca418056a68/tests/data/sidecars/003_MPRAGE_20100603125600.json), but dcm2bids makes a single choice for the result of each (related: #98).

I suspect this means results can be inconsistent. It's not necessarily obvious when criteria overlap (and I'm not going to try to prove it but figuring that out is probably equivalent to [3sat](https://en.wikipedia.org/wiki/Boolean_satisfiability_problem#3-satisfiability) so there's no way we could warn people ahead of time), but when they do what happens is probably going to be that whichever criteria happens to be considered first will win. Python dicts are sorted now, officially, but json isn't, so we can't necessarily trust that users can control this.

We should think this through, maybe detect and throw an exception when it happens (pro: problems are detected early; con: it's possible that configs which run fine on most datasets for months appear to suddenly break when faced with a particularly complicated dataset) or a warning, document it, and maybe try to mitigate it by making `criteria` a list (of one-element objects) instead of a dict.

**Comment by arnaudbore** [comment]
I'm not sure I follow you on this one. For each criteria you end up with True or False and then to be renamed all criteria have to be True. There is no intersect.
